[package]
name = "dear-imgui-test-engine"
version.workspace = true
edition.workspace = true
description = "Safe Rust wrapper for Dear ImGui Test Engine"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
documentation = "https://docs.rs/dear-imgui-test-engine"
categories.workspace = true
keywords.workspace = true
readme = "README.md"

[dependencies]
dear-imgui-rs = { workspace = true, features = ["test-engine"] }
dear-imgui-test-engine-sys.workspace = true
bitflags.workspace = true

[features]
default = ["capture"]
freetype = [
    "dear-imgui-rs/freetype",
    "dear-imgui-test-engine-sys/freetype",
]
capture = ["dear-imgui-test-engine-sys/capture"]
