name: Feature request
description: Suggest a new capability or improvement.
labels: [enhancement, triage]
body:
  - type: checkboxes
    id: crates
    attributes:
      label: Target crates
      description: Which part(s) of the workspace does this affect?
      options:
        - label: dear-imgui-rs
        - label: dear-imgui-sys
        - label: backends (wgpu/glow/winit/sdl3)
        - label: dear-app
        - label: extensions (implot/implot3d/imnodes/imguizmo/imguizmo-quat/file-browser/reflect)
        - label: CI / packaging / prebuilt
        - label: Docs
        - label: Other / Unsure
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the change. Include APIs, flags, or UX where helpful.
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What is explicitly in/out of scope?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How will we know this is done?
