/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ImGuiTestEngine {
    _unused: [u8; 0],
}
pub const ImGuiTestEngineRunSpeed_Fast: ImGuiTestEngineRunSpeed = 0;
pub const ImGuiTestEngineRunSpeed_Normal: ImGuiTestEngineRunSpeed = 1;
pub const ImGuiTestEngineRunSpeed_Cinematic: ImGuiTestEngineRunSpeed = 2;
pub type ImGuiTestEngineRunSpeed = ::std::os::raw::c_uint;
pub const ImGuiTestEngineVerboseLevel_Silent: ImGuiTestEngineVerboseLevel = 0;
pub const ImGuiTestEngineVerboseLevel_Error: ImGuiTestEngineVerboseLevel = 1;
pub const ImGuiTestEngineVerboseLevel_Warning: ImGuiTestEngineVerboseLevel = 2;
pub const ImGuiTestEngineVerboseLevel_Info: ImGuiTestEngineVerboseLevel = 3;
pub const ImGuiTestEngineVerboseLevel_Debug: ImGuiTestEngineVerboseLevel = 4;
pub const ImGuiTestEngineVerboseLevel_Trace: ImGuiTestEngineVerboseLevel = 5;
pub type ImGuiTestEngineVerboseLevel = ::std::os::raw::c_uint;
pub const ImGuiTestEngineGroup_Unknown: ImGuiTestEngineGroup = -1;
pub const ImGuiTestEngineGroup_Tests: ImGuiTestEngineGroup = 0;
pub const ImGuiTestEngineGroup_Perfs: ImGuiTestEngineGroup = 1;
pub type ImGuiTestEngineGroup = ::std::os::raw::c_int;
pub const ImGuiTestEngineRunFlags_None: ImGuiTestEngineRunFlags = 0;
pub const ImGuiTestEngineRunFlags_GuiFuncDisable: ImGuiTestEngineRunFlags = 1;
pub const ImGuiTestEngineRunFlags_GuiFuncOnly: ImGuiTestEngineRunFlags = 2;
pub const ImGuiTestEngineRunFlags_NoSuccessMsg: ImGuiTestEngineRunFlags = 4;
pub const ImGuiTestEngineRunFlags_EnableRawInputs: ImGuiTestEngineRunFlags = 8;
pub const ImGuiTestEngineRunFlags_RunFromGui: ImGuiTestEngineRunFlags = 16;
pub const ImGuiTestEngineRunFlags_RunFromCommandLine: ImGuiTestEngineRunFlags = 32;
pub const ImGuiTestEngineRunFlags_NoError: ImGuiTestEngineRunFlags = 1024;
pub const ImGuiTestEngineRunFlags_ShareVars: ImGuiTestEngineRunFlags = 2048;
pub const ImGuiTestEngineRunFlags_ShareTestContext: ImGuiTestEngineRunFlags = 4096;
pub type ImGuiTestEngineRunFlags = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialEq, Eq)]
pub struct ImGuiTestEngineResultSummary_c {
    pub CountTested: ::std::os::raw::c_int,
    pub CountSuccess: ::std::os::raw::c_int,
    pub CountInQueue: ::std::os::raw::c_int,
}
unsafe extern "C" {
    pub fn imgui_test_engine_create_context() -> *mut ImGuiTestEngine;
}
unsafe extern "C" {
    pub fn imgui_test_engine_destroy_context(engine: *mut ImGuiTestEngine);
}
unsafe extern "C" {
    pub fn imgui_test_engine_start(engine: *mut ImGuiTestEngine, ui_ctx: *mut ImGuiContext);
}
unsafe extern "C" {
    pub fn imgui_test_engine_stop(engine: *mut ImGuiTestEngine);
}
unsafe extern "C" {
    pub fn imgui_test_engine_post_swap(engine: *mut ImGuiTestEngine);
}
unsafe extern "C" {
    pub fn imgui_test_engine_show_windows(engine: *mut ImGuiTestEngine, p_open: *mut bool);
}
unsafe extern "C" {
    pub fn imgui_test_engine_queue_tests(
        engine: *mut ImGuiTestEngine,
        group: ImGuiTestEngineGroup,
        filter: *const ::std::os::raw::c_char,
        run_flags: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn imgui_test_engine_is_test_queue_empty(engine: *mut ImGuiTestEngine) -> bool;
}
unsafe extern "C" {
    pub fn imgui_test_engine_try_abort_engine(engine: *mut ImGuiTestEngine) -> bool;
}
unsafe extern "C" {
    pub fn imgui_test_engine_abort_current_test(engine: *mut ImGuiTestEngine);
}
unsafe extern "C" {
    pub fn imgui_test_engine_get_result_summary(
        engine: *mut ImGuiTestEngine,
        out_summary: *mut ImGuiTestEngineResultSummary_c,
    );
}
unsafe extern "C" {
    pub fn imgui_test_engine_set_run_speed(
        engine: *mut ImGuiTestEngine,
        speed: ImGuiTestEngineRunSpeed,
    );
}
unsafe extern "C" {
    pub fn imgui_test_engine_set_verbose_level(
        engine: *mut ImGuiTestEngine,
        level: ImGuiTestEngineVerboseLevel,
    );
}
unsafe extern "C" {
    pub fn imgui_test_engine_set_capture_enabled(engine: *mut ImGuiTestEngine, enabled: bool);
}
unsafe extern "C" {
    pub fn imgui_test_engine_is_running_tests(engine: *mut ImGuiTestEngine) -> bool;
}
unsafe extern "C" {
    pub fn imgui_test_engine_is_requesting_max_app_speed(engine: *mut ImGuiTestEngine) -> bool;
}
unsafe extern "C" {
    pub fn imgui_test_engine_install_default_crash_handler();
}
