// dear-imgui-rs-binding-provenance-v1 crate=dear-imgui-cte-sys target=wasm source=b340b99748f9b13307a8e88b938c4c9f8d77df48 nested=3b46d759975dfd628ef20fd51b7e1c81ef635be5 spec=fnv1a64:9b1b9365c0a65d0f inputs=fnv1a64:2206402c8f76ec5e output=fnv1a64:92bc8955297ddff8
/* automatically generated by rust-bindgen 0.72.1 */

pub type DocPos = DocPos_c;
pub type DocSelection = DocSelection_c;
pub type VisPos = VisPos_c;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialEq, Eq)]
pub struct DocPos_c {
    pub line: usize,
    pub index: usize,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialEq, Eq)]
pub struct DocSelection_c {
    pub start: DocPos_c,
    pub end: DocPos_c,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialEq, Eq)]
pub struct VisPos_c {
    pub row: usize,
    pub column: usize,
}
pub const alignTop: Scroll = 0;
pub const alignMiddle: Scroll = 1;
pub const alignBottom: Scroll = 2;
pub type Scroll = ::std::os::raw::c_uint;
#[repr(C)]
pub struct Decorator {
    pub line: usize,
    pub width: f32,
    pub height: f32,
    pub glyphSize: ImVec2_c,
    pub userData: *mut ::std::os::raw::c_void,
}
impl Default for Decorator {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
pub struct CustomCaret {
    pub drawList: *mut ImDrawList,
    pub glyphPos: ImVec2_c,
    pub glyphSize: ImVec2_c,
    pub caretVisible: bool,
    pub caretColor: ImU32,
    pub cursorIndex: usize,
}
impl Default for CustomCaret {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct PopupData {
    pub pos: DocPos_c,
    pub userData: *mut ::std::os::raw::c_void,
}
impl Default for PopupData {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialEq, Eq)]
pub struct CodePoint {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialEq, Eq)]
pub struct TextEditor {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Change {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Palette {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Iterator {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Language {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AutoCompleteState {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AutoCompleteConfig {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LineBreakConfig {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialEq, Eq)]
pub struct TextDiff {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialEq, Eq)]
pub struct TrieAutoComplete {
    pub _address: u8,
}
pub const success: Type = 0;
pub const warning: Type = 1;
pub const error: Type = 2;
pub const info: Type = 3;
pub type Type = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Notifications {
    pub _address: u8,
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_TextEditor() -> *mut TextEditor;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_destroy(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn DocPos_DocPos_Nil() -> *mut DocPos;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn DocPos_destroy(self_: *mut DocPos);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn DocPos_DocPos_size_t(line: usize, index: usize) -> *mut DocPos;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn DocSelection_DocSelection_Nil() -> *mut DocSelection;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn DocSelection_destroy(self_: *mut DocSelection);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn DocSelection_DocSelection_DocPos(start: DocPos_c, end: DocPos_c) -> *mut DocSelection;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn VisPos_VisPos_Nil() -> *mut VisPos;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn VisPos_destroy(self_: *mut VisPos);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn VisPos_VisPos_size_t(row: usize, column: usize) -> *mut VisPos;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetTabSize(self_: *mut TextEditor, value: usize);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetTabSize(self_: *mut TextEditor) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetInsertSpacesOnTabs(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsInsertSpacesOnTabs(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetLineSpacing(self_: *mut TextEditor, value: f32);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetLineSpacing(self_: *mut TextEditor) -> f32;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetWordWrapEnabled(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsWordWrapEnabled(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetReadOnlyEnabled(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsReadOnlyEnabled(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetCaretsVisible(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsCaretsVisible(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetAutoIndentEnabled(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsAutoIndentEnabled(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetShowWhitespacesEnabled(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsShowWhitespacesEnabled(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetShowSpacesEnabled(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsShowSpacesEnabled(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetShowTabsEnabled(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsShowTabsEnabled(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetShowLineNumbersEnabled(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsShowLineNumbersEnabled(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetShowMiniMapEnabled(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsShowMiniMapEnabled(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetMiniMapColumns(self_: *mut TextEditor, value: usize);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetMiniMapColumns(self_: *mut TextEditor) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetShowScrollbarMiniMapEnabled(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsShowScrollbarMiniMapEnabled(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetShowPanScrollIndicatorEnabled(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsShowPanScrollIndicatorEnabled(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetShowMatchingBrackets(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsShowingMatchingBrackets(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetCompletePairedGlyphs(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsCompletingPairedGlyphs(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetLineFoldingEnabled(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsLineFoldingEnabled(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetOverwriteEnabled(self_: *mut TextEditor, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsOverwriteEnabled(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetMiddleMousePanMode(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetMiddleMouseScrollMode(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsMiddleMousePanMode(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetLineNumberLeftMargin(self_: *mut TextEditor, value: usize);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetLineNumberLeftMargin(self_: *mut TextEditor) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetDecorationLeftMargin(self_: *mut TextEditor, value: usize);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetDecorationLeftMargin(self_: *mut TextEditor) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetTextLeftMargin(self_: *mut TextEditor, value: usize);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetTextLeftMargin(self_: *mut TextEditor) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetText(self_: *mut TextEditor, text: *const ::std::os::raw::c_char);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetText(self_: *mut TextEditor) -> *const ::std::os::raw::c_char;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetCursorText(
        self_: *mut TextEditor,
        cursor: usize,
    ) -> *const ::std::os::raw::c_char;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetLineText(
        self_: *mut TextEditor,
        line: usize,
    ) -> *const ::std::os::raw::c_char;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetSectionText_DocPos(
        self_: *mut TextEditor,
        start: DocPos_c,
        end: DocPos_c,
    ) -> *const ::std::os::raw::c_char;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetSectionText_DocSelection(
        self_: *mut TextEditor,
        selection: DocSelection_c,
    ) -> *const ::std::os::raw::c_char;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ReplaceSectionText_DocPos(
        self_: *mut TextEditor,
        start: DocPos_c,
        end: DocPos_c,
        text: *const ::std::os::raw::c_char,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ReplaceSectionText_DocSelection(
        self_: *mut TextEditor,
        selection: DocSelection_c,
        text: *const ::std::os::raw::c_char,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ClearText(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsEmpty(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetLineCount(self_: *mut TextEditor) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_Render(
        self_: *mut TextEditor,
        title: *const ::std::os::raw::c_char,
        size: ImVec2_c,
        childFlags: ImGuiChildFlags,
        windowFlags: ImGuiWindowFlags,
    ) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetFocus(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_Cut(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_Copy(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_Paste(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_Undo(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_Redo(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_CanUndo(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_CanRedo(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetUndoIndex(self_: *mut TextEditor) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SelectAll(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SelectLine(self_: *mut TextEditor, line: usize);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SelectLines(self_: *mut TextEditor, start: usize, end: usize);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SelectRegion(self_: *mut TextEditor, start: DocPos_c, end: DocPos_c);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SelectToBrackets(self_: *mut TextEditor, includeBrackets: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GrowSelections(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ShrinkSelections(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_AddNextOccurrence(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SelectAllOccurrences(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_AnyCursorHasSelection(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_AllCursorsHaveSelection(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_CursorHasSelection(self_: *mut TextEditor, cursor: usize) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_MainCursorHasSelection(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_CurrentCursorHasSelection(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ClearCursors(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetNumberOfCursors(self_: *mut TextEditor) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetCursorPosition(self_: *mut TextEditor, cursor: usize) -> DocPos_c;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetMainCursorPosition(self_: *mut TextEditor) -> DocPos_c;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetCurrentCursorPosition(self_: *mut TextEditor) -> DocPos_c;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetCursorSelection(self_: *mut TextEditor, cursor: usize) -> DocSelection_c;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetMainCursorSelection(self_: *mut TextEditor) -> DocSelection_c;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetCurrentCursorSelection(self_: *mut TextEditor) -> DocSelection_c;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsMousePosOverGlyph(self_: *mut TextEditor, mousePos: ImVec2_c) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsMousePosOverTextArea(self_: *mut TextEditor, mousePos: ImVec2_c) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetDocPosAtMousePos(self_: *mut TextEditor, mousePos: ImVec2_c) -> DocPos_c;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetWordAtMousePos(
        self_: *mut TextEditor,
        mousePos: ImVec2_c,
    ) -> *const ::std::os::raw::c_char;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ScrollToLine(self_: *mut TextEditor, line: usize, alignment: Scroll);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetFirstVisibleRow(self_: *mut TextEditor) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetLastVisibleRow(self_: *mut TextEditor) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetFirstVisibleColumn(self_: *mut TextEditor) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetLastVisibleColumn(self_: *mut TextEditor) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetCursor(self_: *mut TextEditor, pos: DocPos_c);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetLineHeight(self_: *mut TextEditor) -> f32;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetGlyphWidth(self_: *mut TextEditor) -> f32;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_DocPos2VisPos(self_: *mut TextEditor, pos: DocPos_c) -> VisPos_c;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_VisPos2DocPos(self_: *mut TextEditor, pos: VisPos_c) -> DocPos_c;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsDocPosVisible(self_: *mut TextEditor, pos: DocPos_c) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsVisPosOverGlyph(self_: *mut TextEditor, pos: VisPos_c) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_FindWordStart(self_: *mut TextEditor, pos: DocPos_c) -> DocPos_c;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_FindWordEnd(self_: *mut TextEditor, pos: DocPos_c) -> DocPos_c;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SelectFirstOccurrenceOf(
        self_: *mut TextEditor,
        text: *const ::std::os::raw::c_char,
        caseSensitive: bool,
        wholeWord: bool,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SelectNextOccurrenceOf(
        self_: *mut TextEditor,
        text: *const ::std::os::raw::c_char,
        caseSensitive: bool,
        wholeWord: bool,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SelectAllOccurrencesOf(
        self_: *mut TextEditor,
        text: *const ::std::os::raw::c_char,
        caseSensitive: bool,
        wholeWord: bool,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ReplaceTextInCurrentCursor(
        self_: *mut TextEditor,
        text: *const ::std::os::raw::c_char,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ReplaceTextInAllCursors(
        self_: *mut TextEditor,
        text: *const ::std::os::raw::c_char,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_OpenFindReplaceWindow(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_CloseFindReplaceWindow(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetFindButtonLabel(
        self_: *mut TextEditor,
        label: *const ::std::os::raw::c_char,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetFindAllButtonLabel(
        self_: *mut TextEditor,
        label: *const ::std::os::raw::c_char,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetReplaceButtonLabel(
        self_: *mut TextEditor,
        label: *const ::std::os::raw::c_char,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetReplaceAllButtonLabel(
        self_: *mut TextEditor,
        label: *const ::std::os::raw::c_char,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_HasFindString(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_FindNext(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_FindAll(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_AddMarker(
        self_: *mut TextEditor,
        line: usize,
        lineNumberColor: ImU32,
        textColor: ImU32,
        lineNumberTooltip: *const ::std::os::raw::c_char,
        textTooltip: *const ::std::os::raw::c_char,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ClearMarkers(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_HasMarkers(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_AddSquiggle(
        self_: *mut TextEditor,
        start: DocPos_c,
        end: DocPos_c,
        type_: usize,
        color: ImU32,
        tooltip: *const ::std::os::raw::c_char,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ClearSquiggles_DocPos(self_: *mut TextEditor, start: DocPos_c, end: DocPos_c);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ClearSquiggles_size_t(self_: *mut TextEditor, type_: usize);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ClearSquiggles_Nil(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_HasSquiggles(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetChangeCallback(
        self_: *mut TextEditor,
        cb: ::std::option::Option<unsafe extern "C" fn()>,
        delay: ::std::os::raw::c_int,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetInsertor(
        self_: *mut TextEditor,
        cb: ::std::option::Option<unsafe extern "C" fn(arg1: usize) -> *mut ::std::os::raw::c_void>,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetDeletor(
        self_: *mut TextEditor,
        cb: ::std::option::Option<
            unsafe extern "C" fn(arg1: usize, arg2: *mut ::std::os::raw::c_void),
        >,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetUserData(
        self_: *mut TextEditor,
        line: usize,
        data: *mut ::std::os::raw::c_void,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetUserData(
        self_: *mut TextEditor,
        line: usize,
    ) -> *mut ::std::os::raw::c_void;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IterateUserData(
        self_: *mut TextEditor,
        cb: ::std::option::Option<
            unsafe extern "C" fn(arg1: usize, arg2: *mut ::std::os::raw::c_void),
        >,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetLineDecorator(
        self_: *mut TextEditor,
        width: usize,
        cb: ::std::option::Option<unsafe extern "C" fn(arg1: *mut Decorator)>,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ClearLineDecorator(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_HasLineDecorator(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetCustomCaretRenderer(
        self_: *mut TextEditor,
        cb: ::std::option::Option<unsafe extern "C" fn(arg1: *const CustomCaret)>,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ClearCustomCaretRenderer(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_HasCustomCaretRenderer(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetLineNumberContextMenuCallback(
        self_: *mut TextEditor,
        cb: ::std::option::Option<unsafe extern "C" fn(arg1: *mut PopupData)>,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ClearLineNumberContextMenuCallback(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_HasLineNumberContextMenuCallback(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetTextContextMenuCallback(
        self_: *mut TextEditor,
        cb: ::std::option::Option<unsafe extern "C" fn(arg1: *mut PopupData)>,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ClearTextContextMenuCallback(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_HasTextContextMenuCallback(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetTextHoverCallback(
        self_: *mut TextEditor,
        cb: ::std::option::Option<unsafe extern "C" fn(arg1: *mut PopupData)>,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ClearTextHoverCallback(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_HasTextHoverCallback(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_FoldAroundLine(self_: *mut TextEditor, line: usize);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_UnfoldAroundLine(self_: *mut TextEditor, line: usize);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ToggleAtLine(self_: *mut TextEditor, line: usize);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_UnfoldAll(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsLineFoldable(self_: *mut TextEditor, line: usize) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsLineFolded(self_: *mut TextEditor, line: usize) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsLineVisible(self_: *mut TextEditor, line: usize) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IsLineHidden(self_: *mut TextEditor, line: usize) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IndentLines(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_DeindentLines(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_MoveUpLines(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_MoveDownLines(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_ToggleComments(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_FilterSelections(
        self_: *mut TextEditor,
        cb: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *const ::std::os::raw::c_char,
            ) -> *const ::std::os::raw::c_char,
        >,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SelectionToLowerCase(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SelectionToUpperCase(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_StripTrailingWhitespaces(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_FilterLines(
        self_: *mut TextEditor,
        cb: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *const ::std::os::raw::c_char,
            ) -> *const ::std::os::raw::c_char,
        >,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_TabsToSpaces(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SpacesToTabs(self_: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Palette_get(self_: *mut Palette, color: Color) -> ImU32;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetPalette(self_: *mut TextEditor, newPalette: *const Palette);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetPalette(self_: *mut TextEditor) -> *const Palette;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetDefaultPalette(aValue: *const Palette);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetDefaultPalette() -> *mut Palette;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetDarkPalette() -> *const Palette;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetLightPalette() -> *const Palette;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Glyph_Glyph_Nil() -> *mut Glyph;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Glyph_destroy(self_: *mut Glyph);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Glyph_Glyph_Wchar(cp: ImWchar) -> *mut Glyph;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Glyph_Glyph_WcharColor(cp: ImWchar, col: Color) -> *mut Glyph;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Iterator_Iterator_Nil() -> *mut Iterator;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Iterator_destroy(self_: *mut Iterator);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Iterator_Iterator_GlyphPtr(g: *mut Glyph) -> *mut Iterator;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Language_C() -> *const Language;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Language_Cpp() -> *const Language;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Language_Cs() -> *const Language;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Language_AngelScript() -> *const Language;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Language_Lua() -> *const Language;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Language_Python() -> *const Language;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Language_Glsl() -> *const Language;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Language_Hlsl() -> *const Language;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Language_Json() -> *const Language;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Language_Markdown() -> *const Language;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Language_Sql() -> *const Language;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetLanguage(self_: *mut TextEditor, language: *const Language);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetLanguage(self_: *mut TextEditor) -> *const Language;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_HasLanguage(self_: *mut TextEditor) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetLanguageName(self_: *mut TextEditor) -> *const ::std::os::raw::c_char;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetLanguageChangeCallback(
        self_: *mut TextEditor,
        cb: ::std::option::Option<unsafe extern "C" fn()>,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_IterateIdentifiers(
        self_: *mut TextEditor,
        cb: ::std::option::Option<unsafe extern "C" fn(arg1: *const ::std::os::raw::c_char)>,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetAutoCompleteConfig(
        self_: *mut TextEditor,
        autoCompleteConfig: *const AutoCompleteConfig,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_write(i: *mut ::std::os::raw::c_char, codepoint: ImWchar) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isLetter(codepoint: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isNumber(codepoint: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isWord(codepoint: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isWhiteSpace(codepoint: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isXidStart(codepoint: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isXidContinue(codepoint: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isLower(codepoint: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isUpper(codepoint: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isEastAsian(codepoint: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_toUpper(codepoint: ImWchar) -> ImWchar;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_toLower(codepoint: ImWchar) -> ImWchar;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isPairOpener(ch: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isPairCloser(ch: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_toPairCloser(ch: ImWchar) -> ImWchar;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_toPairOpener(ch: ImWchar) -> ImWchar;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isMatchingPair(open: ImWchar, close: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isBracketOpener(ch: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isBracketCloser(ch: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn CodePoint_isMatchingBrackets(open: ImWchar, close: ImWchar) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetLineBreakConfig(self_: *mut TextEditor, newConfig: *mut LineBreakConfig);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_SetImGuiContext(ctx: *mut ImGuiContext);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_TextDiff() -> *mut TextDiff;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_destroy(self_: *mut TextDiff);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_SetSideBySideMode(self_: *mut TextDiff, flag: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_GetSideBySideMode(self_: *mut TextDiff) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_SetTabSize(self_: *mut TextDiff, value: usize);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_GetTabSize(self_: *mut TextDiff) -> usize;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_SetLineSpacing(self_: *mut TextDiff, value: f32);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_GetLineSpacing(self_: *mut TextDiff) -> f32;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_SetWordWrapEnabled(self_: *mut TextDiff, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_IsWordWrapEnabled(self_: *mut TextDiff) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_SetShowWhitespacesEnabled(self_: *mut TextDiff, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_IsShowWhitespacesEnabled(self_: *mut TextDiff) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_SetShowSpacesEnabled(self_: *mut TextDiff, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_IsShowSpacesEnabled(self_: *mut TextDiff) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_SetShowTabsEnabled(self_: *mut TextDiff, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_IsShowTabsEnabled(self_: *mut TextDiff) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_SetShowScrollbarMiniMapEnabled(self_: *mut TextDiff, value: bool);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_IsShowScrollbarMiniMapEnabled(self_: *mut TextDiff) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_SetLanguage(self_: *mut TextDiff, language: *const Language);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_GetLanguage(self_: *mut TextDiff) -> *const Language;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_SetColors(self_: *mut TextDiff, ac: ImU32, dc: ImU32);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_SetPalette(self_: *mut TextDiff, newPalette: *const Palette);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_GetPalette(self_: *mut TextDiff) -> *const Palette;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_SetFocus(self_: *mut TextDiff);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_SetText(
        self_: *mut TextDiff,
        left: *const ::std::os::raw::c_char,
        right: *const ::std::os::raw::c_char,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextDiff_Render(
        self_: *mut TextDiff,
        title: *const ::std::os::raw::c_char,
        size: ImVec2_c,
        childFlags: ImGuiChildFlags,
        windowFlags: ImGuiWindowFlags,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TrieAutoComplete_TrieAutoComplete() -> *mut TrieAutoComplete;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TrieAutoComplete_destroy(self_: *mut TrieAutoComplete);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TrieAutoComplete_Connect(self_: *mut TrieAutoComplete, editor: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TrieAutoComplete_Disconnect(self_: *mut TrieAutoComplete);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TrieAutoComplete_IsConnected(self_: *mut TrieAutoComplete) -> bool;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Notifications_Notifications() -> *mut Notifications;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Notifications_destroy(self_: *mut Notifications);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Notifications_Add(
        self_: *mut Notifications,
        type_: Type,
        message: *const ::std::os::raw::c_char,
        dismissTime: ::std::os::raw::c_int,
    );
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Notifications_Render(self_: *mut Notifications, pos: ImVec2_c);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    #[doc = "manual generated"]
    pub fn Palette_Palette() -> *mut Palette;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Palette_destroy(arg1: *mut Palette);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Palette_set(arg1: *mut Palette, arg2: ImU32, arg3: ::std::os::raw::c_int);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn Palette_const_get(arg1: *const Palette, arg2: Color) -> ImU32;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetText_alloc(self_: *mut TextEditor) -> *mut ::std::os::raw::c_char;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetText_free(ptr: *mut ::std::os::raw::c_char);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn TextEditor_GetText_static(self_: *mut TextEditor) -> *const ::std::os::raw::c_char;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    #[doc = "Dejavu"]
    pub fn GetDejavu(deja: *mut *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn SetDejavu();
}
pub const DearImGuiCteStatus_Ok: DearImGuiCteStatus_ = 0;
pub const DearImGuiCteStatus_NullArgument: DearImGuiCteStatus_ = 1;
pub const DearImGuiCteStatus_InvalidValue: DearImGuiCteStatus_ = 2;
pub const DearImGuiCteStatus_CallbackFailed: DearImGuiCteStatus_ = 3;
pub type DearImGuiCteStatus_ = ::std::os::raw::c_uint;
pub use self::DearImGuiCteStatus_ as DearImGuiCteStatus;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DearImGuiCteAutocompleteConfig {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DearImGuiCteAutocompleteState {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct DearImGuiCteAutocompleteContextView {
    pub in_identifier: bool,
    pub in_number: bool,
    pub in_comment: bool,
    pub in_string: bool,
    pub language: *const Language,
    pub application_userdata: *mut ::std::os::raw::c_void,
}
impl Default for DearImGuiCteAutocompleteContextView {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct DearImGuiCteChangeView {
    pub insert: bool,
    pub start: DocPos_c,
    pub end: DocPos_c,
    pub text: *const ::std::os::raw::c_char,
    pub text_len: usize,
}
impl Default for DearImGuiCteChangeView {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type DearImGuiCteChangeCallback =
    ::std::option::Option<unsafe extern "C" fn(userdata: *mut ::std::os::raw::c_void)>;
pub type DearImGuiCteTransactionCallback = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        change: *const DearImGuiCteChangeView,
    ),
>;
pub type DearImGuiCteInsertCallback = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        line: usize,
    ) -> *mut ::std::os::raw::c_void,
>;
pub type DearImGuiCteDeleteCallback = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        line: usize,
        line_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type DearImGuiCteLineDataCallback = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        line: usize,
        line_data: *mut ::std::os::raw::c_void,
    ),
>;
pub type DearImGuiCteDecoratorCallback = ::std::option::Option<
    unsafe extern "C" fn(userdata: *mut ::std::os::raw::c_void, decorator: *mut Decorator),
>;
pub type DearImGuiCteCaretCallback = ::std::option::Option<
    unsafe extern "C" fn(userdata: *mut ::std::os::raw::c_void, caret: *const CustomCaret),
>;
pub type DearImGuiCtePopupCallback = ::std::option::Option<
    unsafe extern "C" fn(userdata: *mut ::std::os::raw::c_void, popup: *mut PopupData),
>;
pub type DearImGuiCteIdentifierCallback = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        identifier: *const ::std::os::raw::c_char,
        identifier_len: usize,
    ),
>;
pub type DearImGuiCteFilterCallback = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        input: *const ::std::os::raw::c_char,
        input_len: usize,
        output: *mut *const ::std::os::raw::c_char,
        output_len: *mut usize,
    ) -> DearImGuiCteStatus,
>;
pub type DearImGuiCteAutocompleteCallback = ::std::option::Option<
    unsafe extern "C" fn(
        userdata: *mut ::std::os::raw::c_void,
        state: *mut DearImGuiCteAutocompleteState,
    ),
>;
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_text_editor_create() -> *mut TextEditor;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_text_editor_destroy(editor: *mut TextEditor);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_text_editor_set_change_callback(
        editor: *mut TextEditor,
        callback: DearImGuiCteChangeCallback,
        userdata: *mut ::std::os::raw::c_void,
        delay_ms: ::std::os::raw::c_int,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_text_editor_reset_autocomplete(
        editor: *mut TextEditor,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_text_editor_clear_callbacks(
        editor: *mut TextEditor,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_set_change_callback(
        editor: *mut TextEditor,
        callback: DearImGuiCteChangeCallback,
        userdata: *mut ::std::os::raw::c_void,
        delay_ms: ::std::os::raw::c_int,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_set_transaction_callback(
        editor: *mut TextEditor,
        callback: DearImGuiCteTransactionCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_set_insert_callback(
        editor: *mut TextEditor,
        callback: DearImGuiCteInsertCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_set_delete_callback(
        editor: *mut TextEditor,
        callback: DearImGuiCteDeleteCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_iterate_line_data(
        editor: *mut TextEditor,
        callback: DearImGuiCteLineDataCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_set_line_decorator(
        editor: *mut TextEditor,
        width: usize,
        callback: DearImGuiCteDecoratorCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_set_custom_caret_callback(
        editor: *mut TextEditor,
        callback: DearImGuiCteCaretCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_set_line_number_context_callback(
        editor: *mut TextEditor,
        callback: DearImGuiCtePopupCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_set_text_context_callback(
        editor: *mut TextEditor,
        callback: DearImGuiCtePopupCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_set_text_hover_callback(
        editor: *mut TextEditor,
        callback: DearImGuiCtePopupCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_set_language_change_callback(
        editor: *mut TextEditor,
        callback: DearImGuiCteChangeCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_iterate_identifiers(
        editor: *mut TextEditor,
        callback: DearImGuiCteIdentifierCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_filter_selections(
        editor: *mut TextEditor,
        callback: DearImGuiCteFilterCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_filter_lines(
        editor: *mut TextEditor,
        callback: DearImGuiCteFilterCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_clear_callbacks(editor: *mut TextEditor) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_config_create() -> *mut DearImGuiCteAutocompleteConfig;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_config_destroy(config: *mut DearImGuiCteAutocompleteConfig);
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_config_set_triggers(
        config: *mut DearImGuiCteAutocompleteConfig,
        on_typing: bool,
        on_shortcut: bool,
        in_comments: bool,
        in_strings: bool,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_config_set_shortcut(
        config: *mut DearImGuiCteAutocompleteConfig,
        shortcut: ImGuiKeyChord,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_config_set_auto_insert_single(
        config: *mut DearImGuiCteAutocompleteConfig,
        enabled: bool,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_config_set_trigger_delay(
        config: *mut DearImGuiCteAutocompleteConfig,
        delay_ms: u64,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_config_set_no_suggestions_label(
        config: *mut DearImGuiCteAutocompleteConfig,
        label: *const ::std::os::raw::c_char,
        label_len: usize,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_config_set_suggestion_width(
        config: *mut DearImGuiCteAutocompleteConfig,
        width: usize,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_config_set_callback(
        config: *mut DearImGuiCteAutocompleteConfig,
        callback: DearImGuiCteAutocompleteCallback,
        userdata: *mut ::std::os::raw::c_void,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_text_editor_set_autocomplete_config(
        editor: *mut TextEditor,
        config: *const DearImGuiCteAutocompleteConfig,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_text_editor_set_autocomplete_suggestions(
        editor: *mut TextEditor,
        suggestions: *const *const ::std::os::raw::c_char,
        suggestion_lengths: *const usize,
        suggestion_count: usize,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_state_get_search_term(
        state: *const DearImGuiCteAutocompleteState,
        text: *mut *const ::std::os::raw::c_char,
        text_len: *mut usize,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_state_get_range(
        state: *const DearImGuiCteAutocompleteState,
        start: *mut DocPos_c,
        end: *mut DocPos_c,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_state_get_context(
        state: *const DearImGuiCteAutocompleteState,
        context: *mut DearImGuiCteAutocompleteContextView,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_state_clear_suggestions(
        state: *mut DearImGuiCteAutocompleteState,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_state_add_suggestion(
        state: *mut DearImGuiCteAutocompleteState,
        suggestion: *const ::std::os::raw::c_char,
        suggestion_len: usize,
    ) -> DearImGuiCteStatus;
}
#[link(wasm_import_module = "imgui-sys-v1")]
unsafe extern "C" {
    pub fn dear_imgui_cte_autocomplete_state_set_promise(
        state: *mut DearImGuiCteAutocompleteState,
        promised: bool,
    ) -> DearImGuiCteStatus;
}
