//! Event handling for Dear ImGui winit backend
//!
//! This module contains event processing logic for various winit events
//! including keyboard, mouse, touch, and IME events.

use dear_imgui_rs::input::MouseSource;
use dear_imgui_rs::{Context, ContextId};
use winit::event::{DeviceEvent, ElementState, Ime, KeyEvent, MouseScrollDelta, TouchPhase};

use std::cell::RefCell;
use std::collections::HashMap;
use winit::window::Window;

use crate::input::{to_imgui_mouse_button, winit_key_to_imgui_key};
use crate::sanitize;

/// Handle keyboard input events
pub fn handle_keyboard_input(event: &KeyEvent, imgui_ctx: &mut Context) -> bool {
    let io = imgui_ctx.io_mut();

    // Inject text for character input on key press (matches upstream imgui-winit behavior)
    if event.state.is_pressed()
        && let Some(txt) = &event.text
    {
        for ch in txt.chars() {
            // Filter out DEL control code as upstream does
            if ch != '\u{7f}' {
                io.add_input_character(ch);
            }
        }
    }

    if let Some(imgui_key) = winit_key_to_imgui_key(&event.logical_key, event.location) {
        let pressed = event.state == ElementState::Pressed;
        io.add_key_event(imgui_key, pressed);
        return io.want_capture_keyboard();
    }

    false
}

/// Handle mouse wheel scrolling
pub fn handle_mouse_wheel(delta: MouseScrollDelta, imgui_ctx: &mut Context) -> bool {
    let io = imgui_ctx.io_mut();

    // Desktop winit mouse wheel events always come from a physical mouse.
    io.add_mouse_source_event(MouseSource::Mouse);

    match delta {
        MouseScrollDelta::LineDelta(h, v) => {
            io.add_mouse_wheel_event([sanitize::finite_or_zero(h), sanitize::finite_or_zero(v)]);
        }
        MouseScrollDelta::PixelDelta(pos) => {
            // Follow upstream practice: treat pixel delta as +/- 1.0 per event
            let h = match pos.x.partial_cmp(&0.0) {
                Some(std::cmp::Ordering::Greater) => 1.0,
                Some(std::cmp::Ordering::Less) => -1.0,
                _ => 0.0,
            };
            let v = match pos.y.partial_cmp(&0.0) {
                Some(std::cmp::Ordering::Greater) => 1.0,
                Some(std::cmp::Ordering::Less) => -1.0,
                _ => 0.0,
            };
            io.add_mouse_wheel_event([h, v]);
        }
    }

    io.want_capture_mouse()
}

/// Handle mouse button events
pub fn handle_mouse_button(
    button: winit::event::MouseButton,
    state: ElementState,
    imgui_ctx: &mut Context,
) -> bool {
    if let Some(imgui_button) = to_imgui_mouse_button(button) {
        let pressed = state == ElementState::Pressed;
        {
            let io = imgui_ctx.io_mut();
            // Mouse button events are generated by a physical mouse here.
            io.add_mouse_source_event(MouseSource::Mouse);
            io.add_mouse_button_event(imgui_button, pressed);
        }
        return imgui_ctx.io().want_capture_mouse();
    }
    false
}

/// Handle cursor movement events
pub fn handle_cursor_moved(position: [f64; 2], imgui_ctx: &mut Context) -> bool {
    let Some(position) = sanitize::finite_vec2_f64_to_f32(position) else {
        return imgui_ctx.io().want_capture_mouse();
    };

    {
        let io = imgui_ctx.io_mut();
        // Cursor move events from winit are produced by a physical mouse.
        io.add_mouse_source_event(MouseSource::Mouse);
        io.add_mouse_pos_event(position);
    }
    imgui_ctx.io().want_capture_mouse()
}

/// Handle modifier key state changes
pub fn handle_modifiers_changed(modifiers: &winit::event::Modifiers, imgui_ctx: &mut Context) {
    let io = imgui_ctx.io_mut();
    let state = modifiers.state();

    // Update modifier key states.
    //
    // Dear ImGui derives `io.KeyMods`/`io.KeyCtrl`/`io.KeyShift`/`io.KeyAlt`/`io.KeySuper`
    // from the `ImGuiMod_*` keys, so we must submit those in addition to the left/right keys.
    //
    // We update both left and right keys to the same state since `ModifiersChanged` doesn't
    // reliably distinguish them across platforms.
    io.add_key_event(dear_imgui_rs::Key::ModShift, state.shift_key());
    io.add_key_event(dear_imgui_rs::Key::LeftShift, state.shift_key());
    io.add_key_event(dear_imgui_rs::Key::RightShift, state.shift_key());
    io.add_key_event(dear_imgui_rs::Key::ModCtrl, state.control_key());
    io.add_key_event(dear_imgui_rs::Key::LeftCtrl, state.control_key());
    io.add_key_event(dear_imgui_rs::Key::RightCtrl, state.control_key());
    io.add_key_event(dear_imgui_rs::Key::ModAlt, state.alt_key());
    io.add_key_event(dear_imgui_rs::Key::LeftAlt, state.alt_key());
    io.add_key_event(dear_imgui_rs::Key::RightAlt, state.alt_key());
    io.add_key_event(dear_imgui_rs::Key::ModSuper, state.super_key());
    io.add_key_event(dear_imgui_rs::Key::LeftSuper, state.super_key());
    io.add_key_event(dear_imgui_rs::Key::RightSuper, state.super_key());
}

/// Handle IME (Input Method Editor) events for international text input
pub fn handle_ime_event(ime: &Ime, imgui_ctx: &mut Context) {
    match ime {
        Ime::Preedit(_text, _cursor_range) => {
            // Do not inject preedit text into Dear ImGui; composition should be handled by the OS/IME.
        }
        Ime::Commit(text) => {
            // Handle committed text (final text input)
            for ch in text.chars() {
                if !ch.is_control() {
                    imgui_ctx.io_mut().add_input_character(ch);
                }
            }
        }
        Ime::Enabled => {
            // IME was enabled - we could set a flag here if needed
        }
        Ime::Disabled => {
            // IME was disabled - we could clear a flag here if needed
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum TouchAction {
    Press,
    Move,
    Release,
}

fn touch_transition(
    active_id: Option<u64>,
    event_id: u64,
    phase: TouchPhase,
) -> (Option<u64>, Option<TouchAction>) {
    match phase {
        TouchPhase::Started if active_id.is_none() => (Some(event_id), Some(TouchAction::Press)),
        TouchPhase::Moved if active_id == Some(event_id) => (active_id, Some(TouchAction::Move)),
        TouchPhase::Ended | TouchPhase::Cancelled if active_id == Some(event_id) => {
            (None, Some(TouchAction::Release))
        }
        _ => (active_id, None),
    }
}

fn context_touch_transition(
    active_touches: &mut HashMap<ContextId, u64>,
    context: ContextId,
    event_id: u64,
    phase: TouchPhase,
) -> Option<TouchAction> {
    let (next_active, action) =
        touch_transition(active_touches.get(&context).copied(), event_id, phase);
    match next_active {
        Some(active_id) => {
            active_touches.insert(context, active_id);
        }
        None => {
            active_touches.remove(&context);
        }
    }
    action
}

pub(crate) fn touch_logical_position(
    touch: &winit::event::Touch,
    window: &Window,
) -> Option<[f32; 2]> {
    let position = touch
        .location
        .to_logical::<f64>(sanitize::positive_finite_or(window.scale_factor(), 1.0));
    sanitize::finite_position(position)
}

pub(crate) fn handle_touch_event_at(
    touch: &winit::event::Touch,
    position: Option<[f32; 2]>,
    viewport: Option<dear_imgui_rs::Id>,
    imgui_ctx: &mut Context,
) -> bool {
    thread_local! {
        static ACTIVE_TOUCHES: RefCell<HashMap<ContextId, u64>> = RefCell::new(HashMap::new());
    }

    let context = imgui_ctx.id();
    ACTIVE_TOUCHES.with(|active_touches| {
        if position.is_none() && matches!(touch.phase, TouchPhase::Started | TouchPhase::Moved) {
            return false;
        }

        let Some(action) = context_touch_transition(
            &mut active_touches.borrow_mut(),
            context,
            touch.id,
            touch.phase,
        ) else {
            return false;
        };

        let io = imgui_ctx.io_mut();
        io.add_mouse_source_event(MouseSource::TouchScreen);
        if let Some(viewport) = viewport {
            io.add_mouse_viewport_event(viewport);
        }
        if let Some(position) = position {
            io.add_mouse_pos_event(position);
        }
        match action {
            TouchAction::Press => {
                io.add_mouse_button_event(dear_imgui_rs::input::MouseButton::Left, true);
            }
            TouchAction::Move => {}
            TouchAction::Release => {
                io.add_mouse_button_event(dear_imgui_rs::input::MouseButton::Left, false);
            }
        }
        true
    })
}

/// Handle touch events by converting them to mouse events.
pub fn handle_touch_event(touch: &winit::event::Touch, window: &Window, imgui_ctx: &mut Context) {
    let position = touch_logical_position(touch, window);
    let _ = handle_touch_event_at(touch, position, None, imgui_ctx);
}

/// Handle device events (raw input events)
pub fn handle_device_event(_event: &DeviceEvent) {
    // Handle device-specific events if needed
    // Currently no specific handling required
}

/// Handle window focus events
pub fn handle_focused(focused: bool, imgui_ctx: &mut Context) -> bool {
    // Tell Dear ImGui about host window focus change
    imgui_ctx.io_mut().add_focus_event(focused);
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_util::test_sync::lock_context;
    use dear_imgui_rs::Context;
    use winit::event::{ElementState, MouseButton, TouchPhase};
    use winit::keyboard::ModifiersState;

    #[test]
    fn test_keyboard_input_handling() {
        // We can't construct KeyEvent directly due to private fields
        // So we'll just test that the function exists and can be called
        // In a real scenario, KeyEvent would be provided by winit

        // Test that the function exists and can be called
        // We'll use a dummy test that doesn't require constructing KeyEvent
        // This is a placeholder test - in a real implementation we would test actual key handling
    }

    #[test]
    fn test_mouse_button_handling() {
        let _guard = lock_context();
        let mut ctx = Context::create();

        let handled = handle_mouse_button(MouseButton::Left, ElementState::Pressed, &mut ctx);
        // The result depends on whether imgui wants to capture mouse
        // We just test that it doesn't panic
        // Test that the function returns a boolean value (always true)
        let _ = handled; // Just verify it's a boolean
    }

    #[test]
    fn test_cursor_moved() {
        let _guard = lock_context();
        let mut ctx = Context::create();

        let handled = handle_cursor_moved([100.0, 200.0], &mut ctx);
        // The result depends on whether imgui wants to capture mouse
        // We just test that it doesn't panic
        // Test that the function returns a boolean value (always true)
        let _ = handled; // Just verify it's a boolean
    }

    #[test]
    fn test_cursor_moved_ignores_non_finite_position() {
        let _guard = lock_context();
        let mut ctx = Context::create();

        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            handle_cursor_moved([f64::NAN, f64::INFINITY], &mut ctx);
        }));

        assert!(result.is_ok());
    }

    #[test]
    fn test_mouse_wheel_ignores_non_finite_line_delta() {
        let _guard = lock_context();
        let mut ctx = Context::create();

        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            handle_mouse_wheel(
                MouseScrollDelta::LineDelta(f32::NAN, f32::INFINITY),
                &mut ctx,
            );
        }));

        assert!(result.is_ok());
    }

    #[test]
    fn test_modifiers_changed_updates_key_mods() {
        let _guard = lock_context();
        let mut ctx = Context::create();
        let io = ctx.io_mut();
        io.set_display_size([1.0, 1.0]);
        io.set_backend_flags(
            io.backend_flags() | dear_imgui_rs::BackendFlags::RENDERER_HAS_TEXTURES,
        );
        ctx.font_atlas().build();

        let macos_behaviors = ctx.io().config_macosx_behaviors();
        let modifiers: winit::event::Modifiers = ModifiersState::CONTROL.into();
        handle_modifiers_changed(&modifiers, &mut ctx);

        let ui = ctx.frame();
        if macos_behaviors {
            assert!(!ui.io().key_ctrl());
            assert!(ui.io().key_super());
        } else {
            assert!(ui.io().key_ctrl());
            assert!(!ui.io().key_super());
        }
        assert!(!ui.io().key_shift());
        assert!(!ui.io().key_alt());
    }

    #[test]
    fn touch_transition_keeps_the_first_finger_until_release() {
        assert_eq!(
            touch_transition(None, 7, TouchPhase::Started),
            (Some(7), Some(TouchAction::Press))
        );
        assert_eq!(
            touch_transition(Some(7), 8, TouchPhase::Started),
            (Some(7), None)
        );
        assert_eq!(
            touch_transition(Some(7), 7, TouchPhase::Moved),
            (Some(7), Some(TouchAction::Move))
        );
        assert_eq!(
            touch_transition(Some(7), 7, TouchPhase::Ended),
            (None, Some(TouchAction::Release))
        );
    }

    #[test]
    fn active_touch_is_isolated_per_context() {
        let _guard = lock_context();
        let context_a = Context::create();
        let context_a_id = context_a.id();
        let context_a = context_a.suspend();
        let context_b = Context::create();
        let context_b_id = context_b.id();
        let mut active_touches = HashMap::new();

        assert_eq!(
            context_touch_transition(&mut active_touches, context_a_id, 7, TouchPhase::Started,),
            Some(TouchAction::Press)
        );
        assert_eq!(
            context_touch_transition(&mut active_touches, context_b_id, 9, TouchPhase::Started,),
            Some(TouchAction::Press)
        );
        assert_eq!(active_touches.get(&context_a_id), Some(&7));
        assert_eq!(active_touches.get(&context_b_id), Some(&9));

        drop(context_b);
        drop(context_a.activate().unwrap());
    }
}
