use anyhow::{Context, Result};
use build_support::binding::{
    BindingFormatter, BindingOwner, BindingRustEdition, BindingSpec, BindingTarget,
    CANONICAL_BINDING_LIBCLANG_VERSION, CANONICAL_BINDING_RUSTC_VERSION,
    CANONICAL_BINDING_RUSTFMT_VERSION, CrateBindingDefine, CrateBindingIncludeRoot,
    CrateBindingLanguage, CrateBindingSpec, CrateBindingTarget, ExtensionBinding, NativeAbiProfile,
    validate_bindgen_environment,
};
use std::{
    borrow::Cow,
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

mod release_version;

const NATIVE_BINDINGS_PREAMBLE: &str = "// AUTOGENERATED: pregenerated bindings for docs.rs/offline builds\n// Note: inner attributes are intentionally omitted to avoid include-context errors.\n\n";

fn core_wasm_import_module() -> &'static str {
    &build_support::source_inventory::SourceInventory::embedded().wasm_import_module
}

fn maintained_source(
    crate_name: &str,
) -> Result<&'static build_support::source_inventory::MaintainedSource> {
    build_support::source_inventory::SourceInventory::embedded()
        .require_source_by_crate(crate_name)
        .map_err(anyhow::Error::from)
}

fn maintained_crate_root(root: &Path, crate_name: &str) -> Result<PathBuf> {
    Ok(root.join(&maintained_source(crate_name)?.crate_root))
}

fn maintained_source_root(root: &Path, crate_name: &str) -> Result<PathBuf> {
    let source = maintained_source(crate_name)?;
    source
        .resolve_source_root(root.join(&source.crate_root))
        .map_err(anyhow::Error::from)
}

fn project_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
}

fn run() -> Result<()> {
    let args = std::env::args().skip(1).collect::<Vec<_>>();
    let Some(cmd) = args.first().map(String::as_str) else {
        print_help();
        anyhow::bail!("an explicit xtask command is required");
    };
    match cmd {
        "wasm-bindgen" => {
            reject_extra_arguments(cmd, &args[1..])?;
            gen_wasm_bindings()?;
        }
        "wasm-bindgen-implot" => {
            reject_extra_arguments(cmd, &args[1..])?;
            gen_implot_wasm_bindings()?;
        }
        "wasm-bindgen-implot3d" => {
            reject_extra_arguments(cmd, &args[1..])?;
            gen_implot3d_wasm_bindings()?;
        }
        "wasm-bindgen-imnodes" => {
            reject_extra_arguments(cmd, &args[1..])?;
            gen_imnodes_wasm_bindings()?;
        }
        "wasm-bindgen-imguizmo" => {
            reject_extra_arguments(cmd, &args[1..])?;
            gen_imguizmo_wasm_bindings()?;
        }
        "wasm-bindgen-imguizmo-quat" => {
            reject_extra_arguments(cmd, &args[1..])?;
            gen_imguizmo_quat_wasm_bindings()?;
        }
        "verify-bindings" => verify_core_bindings(&args[1..])?,
        "release-version" => release_version::run(&project_root(), &args[1..])?,
        "web-demo" => build_web_demo(optional_single_argument(cmd, &args[1..])?)?,
        "build-cimgui-provider" => {
            let options = BuildProviderOptions::parse(&project_root(), &args[1..])?;
            build_cimgui_provider(options)?;
        }
        "help" | "-h" | "--help" => {
            reject_extra_arguments(cmd, &args[1..])?;
            print_help();
        }
        _ => {
            print_help();
            anyhow::bail!("unknown xtask command: {cmd}");
        }
    }
    Ok(())
}

fn print_help() {
    eprintln!(
        "Commands:\n  wasm-bindgen\n  wasm-bindgen-implot\n  wasm-bindgen-implot3d\n  wasm-bindgen-imnodes\n  wasm-bindgen-imguizmo\n  wasm-bindgen-imguizmo-quat\n  verify-bindings [--check-only | --update] [--allow-dirty]\n  release-version <semver> [--dry-run] [--allow-prerelease-relabel]\n  web-demo [feature_list]\n  build-cimgui-provider [--source-root PATH] [--inventory PATH] [--out-dir PATH]\n  help\n\nExamples:\n  # Verify checked-in core bindings and git state\n  xtask verify-bindings\n  # Regenerate all supported core binding profiles\n  xtask verify-bindings --update --allow-dirty\n  # Preview a stable-to-prerelease release-train relabel\n  xtask release-version 0.16.0-alpha.1 --allow-prerelease-relabel --dry-run\n  # Core ImGui only\n  xtask web-demo\n  # ImGui + ImPlot\n  xtask web-demo implot\n  # ImGui + ImPlot + ImNodes\n  xtask web-demo implot,imnodes"
    );
}

fn reject_extra_arguments(command: &str, arguments: &[String]) -> Result<()> {
    if !arguments.is_empty() {
        anyhow::bail!(
            "{command} does not accept arguments: {}",
            arguments.join(" ")
        );
    }
    Ok(())
}

fn optional_single_argument<'a>(command: &str, arguments: &'a [String]) -> Result<Option<&'a str>> {
    if arguments.len() > 1 {
        anyhow::bail!(
            "{command} accepts at most one argument, got: {}",
            arguments.join(" ")
        );
    }
    Ok(arguments.first().map(String::as_str))
}

fn gen_wasm_bindings() -> Result<()> {
    let root = project_root();
    let sys_root = maintained_crate_root(&root, "dear-imgui-sys")?;
    let out = sys_root.join("src").join("wasm_bindings_pregenerated.rs");
    let spec = BindingSpec::core_wasm(core_wasm_import_module());

    eprintln!(
        "Generating wasm bindings to {} (import module: {})",
        out.display(),
        core_wasm_import_module()
    );
    generate_core_bindings(&root, &spec, &out)?;
    eprintln!("Done.");
    Ok(())
}

fn core_bindgen_builder(
    root: &Path,
    spec: &BindingSpec,
    target_override: Option<&str>,
) -> Result<bindgen::Builder> {
    let cimgui_root = maintained_source_root(root, "dear-imgui-sys")?;
    let shim_root = root
        .join("target/binding-spec-headers")
        .join(spec.deterministic_hash().replace(':', "-"));
    fs::create_dir_all(&shim_root)
        .with_context(|| format!("create binding header shim dir {}", shim_root.display()))?;
    for shim in spec.header_shims {
        fs::write(shim_root.join(shim.name), shim.contents)
            .with_context(|| format!("write binding header shim {}", shim.name))?;
    }
    let wrapper = format!("{}\n#include \"{}\"\n", spec.header_preamble, spec.header);
    let mut builder =
        bindgen::Builder::default().header_contents("dear_imgui_rs_bindings.h", &wrapper);
    builder = match spec.formatter {
        BindingFormatter::Rustfmt => builder.formatter(bindgen::Formatter::Rustfmt),
    };
    builder = match spec.rust_edition {
        BindingRustEdition::Rust2021 => builder.rust_edition(bindgen::RustEdition::Edition2021),
    };
    builder = builder.clang_arg(format!("-I{}", shim_root.display()));
    for include in spec.include_paths {
        builder = builder.clang_arg(format!("-I{}", cimgui_root.join(include).display()));
    }
    for arg in spec.clang_args {
        if target_override.is_none() || !arg.starts_with("--target=") {
            builder = builder.clang_arg(*arg);
        }
    }
    if let Some(target) = target_override {
        builder = builder.clang_arg(format!("--target={target}"));
    }
    for define in spec.clang_defines {
        builder = builder.clang_arg(format!("-D{define}"));
    }
    for pattern in spec.allowlisted_functions {
        builder = builder.allowlist_function(pattern);
    }
    for pattern in spec.blocklisted_functions {
        builder = builder.blocklist_function(pattern);
    }
    for pattern in spec.allowlisted_types {
        builder = builder.allowlist_type(pattern);
    }
    for pattern in spec.blocklisted_types {
        builder = builder.blocklist_type(pattern);
    }
    for pattern in spec.allowlisted_vars {
        builder = builder.allowlist_var(pattern);
    }
    for line in spec.raw_lines {
        builder = builder.raw_line(*line);
    }
    builder = builder
        .derive_default(spec.derives.default)
        .derive_debug(spec.derives.debug)
        .derive_copy(spec.derives.copy)
        .derive_eq(spec.derives.eq)
        .derive_partialeq(spec.derives.partial_eq)
        .derive_hash(spec.derives.hash)
        .prepend_enum_name(spec.prepend_enum_name)
        .layout_tests(spec.layout_tests);
    if let BindingTarget::WasmImport { module_name } = &spec.target {
        builder = builder.wasm_import_module_name(module_name);
    }
    Ok(builder)
}

fn generate_core_bindings(root: &Path, spec: &BindingSpec, output: &Path) -> Result<()> {
    generate_core_bindings_for_target(root, spec, None, output)
}

fn generate_core_bindings_for_target(
    root: &Path,
    spec: &BindingSpec,
    target_override: Option<&str>,
    output: &Path,
) -> Result<()> {
    let environment_names = std::env::vars_os()
        .map(|(name, _)| name.to_string_lossy().into_owned())
        .collect::<Vec<_>>();
    validate_bindgen_environment(&environment_names).map_err(anyhow::Error::msg)?;
    let bindings = core_bindgen_builder(root, spec, target_override)?
        .generate()
        .context("bindgen generate() failed for Dear ImGui core")?;
    bindings
        .write_to_file(output)
        .with_context(|| format!("write bindings to {}", output.display()))?;
    let content = std::fs::read_to_string(output)
        .with_context(|| format!("read generated bindings from {}", output.display()))?;
    let content = spec.sanitize(&content);
    spec.validate_generated_bindings(&content)
        .map_err(anyhow::Error::msg)?;
    std::fs::write(output, content)
        .with_context(|| format!("write sanitized bindings to {}", output.display()))?;
    Ok(())
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
struct VerifyBindingOptions {
    check_only: bool,
    allow_dirty: bool,
    update: bool,
}

impl VerifyBindingOptions {
    fn parse(args: &[String]) -> Result<Self> {
        let mut options = Self::default();
        for arg in args {
            match arg.as_str() {
                "--check-only" if !options.check_only => options.check_only = true,
                "--allow-dirty" if !options.allow_dirty => options.allow_dirty = true,
                "--update" if !options.update => options.update = true,
                "--check-only" | "--allow-dirty" | "--update" => {
                    anyhow::bail!("verify-bindings option may only be specified once: {arg}")
                }
                _ => anyhow::bail!("unknown verify-bindings option: {arg}"),
            }
        }
        if options.check_only && options.update {
            anyhow::bail!("--check-only and --update cannot be combined");
        }
        Ok(options)
    }
}

fn verify_core_bindings(args: &[String]) -> Result<()> {
    use std::process::Command;

    let options = VerifyBindingOptions::parse(args)?;
    let root = project_root();
    let sys_root = maintained_crate_root(&root, "dear-imgui-sys")?;
    let bindings_dir = sys_root.join("src");
    let wasm_path = bindings_dir.join("wasm_bindings_pregenerated.rs");
    let native_profiles = [NativeAbiProfile::Windows64, NativeAbiProfile::NonWindows];
    let wasm_spec = BindingSpec::core_wasm(core_wasm_import_module());

    if !options.update {
        for profile in native_profiles {
            let path = sys_root.join(profile.pregenerated_file());
            validate_checked_in_bindings(&path, &BindingSpec::core_native(profile))?;
        }
        validate_checked_in_bindings(&wasm_path, &wasm_spec)?;
        validate_checked_in_extension_bindings(&root)?;
    }

    if !options.check_only {
        validate_canonical_binding_toolchain()?;
        let target_dir = root.join("target");
        fs::create_dir_all(&target_dir)
            .with_context(|| format!("create {}", target_dir.display()))?;
        let verification_dir = tempfile::Builder::new()
            .prefix("binding-verification-")
            .tempdir_in(&target_dir)
            .context("create independent binding verification directory")?;
        let first_dir = verification_dir.path().join("first");
        let second_dir = verification_dir.path().join("second");
        fs::create_dir_all(&first_dir)
            .with_context(|| format!("create {}", first_dir.display()))?;
        fs::create_dir_all(&second_dir)
            .with_context(|| format!("create {}", second_dir.display()))?;
        let mut generated_native_profiles = Vec::new();
        for profile in native_profiles {
            let spec = BindingSpec::core_native(profile);
            let file_name = format!("bindings_{}.rs", profile.id());
            let first_native = first_dir.join(&file_name);
            let second_native = second_dir.join(&file_name);
            generate_core_bindings(&root, &spec, &first_native)?;
            generate_core_bindings(&root, &spec, &second_native)?;
            let canonical = fs::read_to_string(&first_native)
                .with_context(|| format!("read {}", first_native.display()))?;
            let repeated = fs::read_to_string(&second_native)
                .with_context(|| format!("read {}", second_native.display()))?;
            require_byte_identical(
                &format!("core native profile {}", profile.id()),
                &canonical,
                &repeated,
            )?;

            for target in profile.compatibility_targets() {
                let compat_name = format!(
                    "bindings_{}_{}.rs",
                    profile.id(),
                    target.rust_target.replace('-', "_")
                );
                let first_compat = first_dir.join(&compat_name);
                let second_compat = second_dir.join(&compat_name);
                generate_core_bindings_for_target(
                    &root,
                    &spec,
                    Some(target.clang_target),
                    &first_compat,
                )?;
                generate_core_bindings_for_target(
                    &root,
                    &spec,
                    Some(target.clang_target),
                    &second_compat,
                )?;
                let compatible = fs::read_to_string(&first_compat)
                    .with_context(|| format!("read {}", first_compat.display()))?;
                let repeated_compat = fs::read_to_string(&second_compat)
                    .with_context(|| format!("read {}", second_compat.display()))?;
                require_byte_identical(
                    &format!("core compatibility target {}", target.rust_target),
                    &compatible,
                    &repeated_compat,
                )?;
                if compatible != canonical {
                    anyhow::bail!(
                        "native ABI profile {} drifts for Rust target {} (clang target {})",
                        profile.id(),
                        target.rust_target,
                        target.clang_target,
                    );
                }
            }
            generated_native_profiles.push((profile, spec, canonical));
        }
        let first_wasm = first_dir.join("bindings_wasm.rs");
        let second_wasm = second_dir.join("bindings_wasm.rs");
        generate_core_bindings(&root, &wasm_spec, &first_wasm)?;
        generate_core_bindings(&root, &wasm_spec, &second_wasm)?;
        let wasm = fs::read_to_string(&first_wasm)
            .with_context(|| format!("read {}", first_wasm.display()))?;
        let repeated_wasm = fs::read_to_string(&second_wasm)
            .with_context(|| format!("read {}", second_wasm.display()))?;
        require_byte_identical("core WASM profile", &wasm, &repeated_wasm)?;
        if options.update {
            for (profile, _, native) in &generated_native_profiles {
                let path = sys_root.join(profile.pregenerated_file());
                std::fs::write(&path, format!("{NATIVE_BINDINGS_PREAMBLE}{native}"))
                    .with_context(|| format!("write {}", path.display()))?;
            }
            std::fs::write(&wasm_path, wasm)
                .with_context(|| format!("write {}", wasm_path.display()))?;
        } else {
            for (profile, _, native) in &generated_native_profiles {
                let path = sys_root.join(profile.pregenerated_file());
                compare_binding_contents(&path, &format!("{NATIVE_BINDINGS_PREAMBLE}{native}"))?;
            }
            compare_binding_contents(&wasm_path, &wasm)?;
        }

        verify_crate_binding_sources(&root)?;
        let first_extension_dir = first_dir.join("extensions");
        let second_extension_dir = second_dir.join("extensions");
        fs::create_dir_all(&first_extension_dir)
            .with_context(|| format!("create {}", first_extension_dir.display()))?;
        fs::create_dir_all(&second_extension_dir)
            .with_context(|| format!("create {}", second_extension_dir.display()))?;
        for spec in CrateBindingSpec::maintained() {
            let file_name = format!("{}_{}.rs", spec.crate_name, spec.target.id());
            let first_path = first_extension_dir.join(&file_name);
            let second_path = second_extension_dir.join(&file_name);
            let generated = generate_extension_bindings(&root, spec, &first_path)?;
            let repeated = generate_extension_bindings(&root, spec, &second_path)?;
            require_byte_identical(
                &format!("{} {} profile", spec.crate_name, spec.target.id()),
                &generated,
                &repeated,
            )?;
            let checked_in_path = root.join(spec.crate_root()).join(spec.checked_in_path);
            if options.update {
                fs::write(&checked_in_path, generated)
                    .with_context(|| format!("write {}", checked_in_path.display()))?;
            } else {
                compare_binding_contents(&checked_in_path, &generated)?;
            }
        }
    }

    for profile in native_profiles {
        let path = sys_root.join(profile.pregenerated_file());
        validate_checked_in_bindings(&path, &BindingSpec::core_native(profile))?;
    }
    validate_checked_in_bindings(&wasm_path, &wasm_spec)?;
    validate_checked_in_extension_bindings(&root)?;

    let wasm_content = std::fs::read_to_string(&wasm_path)
        .with_context(|| format!("read {}", wasm_path.display()))?;
    let import_module = core_wasm_import_module();
    let expected_import = format!("#[link(wasm_import_module = \"{import_module}\")]");
    if !wasm_content.contains(&expected_import) {
        anyhow::bail!(
            "{} does not use the supported import provider {import_module}",
            wasm_path.display()
        );
    }

    if !options.allow_dirty {
        let core_crate_root = &maintained_source("dear-imgui-sys")?.crate_root;
        let mut binding_paths = vec![
            format!("{core_crate_root}/src/bindings_pregenerated.rs"),
            format!("{core_crate_root}/src/bindings_pregenerated_windows.rs"),
            format!("{core_crate_root}/src/wasm_bindings_pregenerated.rs"),
        ];
        binding_paths.extend(
            CrateBindingSpec::maintained()
                .iter()
                .map(|spec| format!("{}/{}", spec.crate_root(), spec.checked_in_path)),
        );
        binding_paths.sort_unstable();
        binding_paths.dedup();
        let output = Command::new("git")
            .current_dir(&root)
            .args(["status", "--porcelain=v1", "--untracked-files=all", "--"])
            .args(&binding_paths)
            .output()
            .context("run git status for checked-in bindings")?;
        if !output.status.success() {
            anyhow::bail!("git status failed while checking binding artifacts");
        }
        if !output.stdout.is_empty() {
            anyhow::bail!(
                "checked-in binding artifacts are dirty:\n{}",
                String::from_utf8_lossy(&output.stdout)
            );
        }
    }

    eprintln!(
        "Core and crate-local bindings verified (windows hash {}, non-windows hash {}, wasm hash {}, extension profiles {})",
        BindingSpec::core_native(NativeAbiProfile::Windows64).deterministic_hash(),
        BindingSpec::core_native(NativeAbiProfile::NonWindows).deterministic_hash(),
        wasm_spec.deterministic_hash(),
        CrateBindingSpec::maintained().len()
    );
    Ok(())
}

fn validate_canonical_binding_toolchain() -> Result<()> {
    use std::process::Command;

    let clang = bindgen::clang_version();
    if clang.parsed != Some(CANONICAL_BINDING_LIBCLANG_VERSION) {
        anyhow::bail!(
            "canonical binding generation requires libclang {}.{}, found {}",
            CANONICAL_BINDING_LIBCLANG_VERSION.0,
            CANONICAL_BINDING_LIBCLANG_VERSION.1,
            clang.full
        );
    }
    for (program, expected) in [
        ("rustc", CANONICAL_BINDING_RUSTC_VERSION),
        ("rustfmt", CANONICAL_BINDING_RUSTFMT_VERSION),
    ] {
        let output = Command::new(program)
            .arg("--version")
            .output()
            .with_context(|| format!("run {program} --version"))?;
        if !output.status.success() {
            anyhow::bail!("{program} --version failed");
        }
        let actual = String::from_utf8_lossy(&output.stdout);
        if !actual.starts_with(expected) {
            anyhow::bail!(
                "canonical binding generation requires {expected}, found {}",
                actual.trim()
            );
        }
    }
    Ok(())
}

fn validate_checked_in_extension_bindings(root: &Path) -> Result<()> {
    for spec in CrateBindingSpec::maintained() {
        let crate_root = root.join(spec.crate_root());
        spec.load_and_validate_full(&crate_root)
            .map_err(anyhow::Error::msg)
            .with_context(|| {
                format!(
                    "validate {} {} checked-in bindings",
                    spec.crate_name,
                    spec.target.id()
                )
            })?;
    }
    Ok(())
}

fn verify_crate_binding_sources(root: &Path) -> Result<()> {
    use build_support::binding::parse_crate_binding_source_revision;
    use std::collections::BTreeSet;
    use std::process::Command;

    let mut crates = BTreeSet::new();
    for spec in CrateBindingSpec::maintained() {
        if !crates.insert(spec.crate_name) {
            continue;
        }
        let crate_root = root.join(spec.crate_root());
        let source_root = crate_root.join(spec.source_root());
        let manifest_path = crate_root.join("Cargo.toml");
        let manifest = fs::read_to_string(&manifest_path)
            .with_context(|| format!("read {}", manifest_path.display()))?;
        let expected =
            parse_crate_binding_source_revision(&manifest).map_err(anyhow::Error::msg)?;

        let top_level = git_output(&source_root, &["rev-parse", "--show-toplevel"])?;
        let actual_top_level = fs::canonicalize(top_level.trim())
            .with_context(|| format!("resolve Git top-level for {}", source_root.display()))?;
        let expected_top_level = fs::canonicalize(&source_root)
            .with_context(|| format!("resolve source root {}", source_root.display()))?;
        if actual_top_level != expected_top_level {
            anyhow::bail!(
                "{} source is not the expected Git worktree: expected {}, found {}",
                spec.crate_name,
                expected_top_level.display(),
                actual_top_level.display()
            );
        }

        let status = git_output(
            &source_root,
            &[
                "status",
                "--porcelain=v1",
                "--untracked-files=all",
                "--ignore-submodules=none",
            ],
        )?;
        if !status.is_empty() {
            anyhow::bail!(
                "{} binding source is dirty at {}:\n{}",
                spec.crate_name,
                source_root.display(),
                status.trim_end()
            );
        }
        let actual = git_output(&source_root, &["rev-parse", "HEAD"])?;
        if actual.trim() != expected {
            anyhow::bail!(
                "{} binding source revision mismatch: metadata {}, HEAD {}",
                spec.crate_name,
                expected,
                actual.trim()
            );
        }
    }

    fn git_output(path: &Path, args: &[&str]) -> Result<String> {
        let output = Command::new("git")
            .arg("-C")
            .arg(path)
            .args(args)
            .output()
            .with_context(|| format!("run git for {}", path.display()))?;
        if !output.status.success() {
            anyhow::bail!(
                "git {} failed for {}: {}",
                args.join(" "),
                path.display(),
                String::from_utf8_lossy(&output.stderr).trim()
            );
        }
        Ok(String::from_utf8_lossy(&output.stdout).into_owned())
    }

    Ok(())
}

fn validate_checked_in_bindings(path: &Path, spec: &BindingSpec) -> Result<()> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("read checked-in bindings from {}", path.display()))?;
    spec.validate_generated_bindings(&content)
        .map_err(anyhow::Error::msg)
        .with_context(|| format!("validate {}", path.display()))
}

fn compare_binding_contents(path: &Path, generated: &str) -> Result<()> {
    let checked_in = std::fs::read_to_string(path)
        .with_context(|| format!("read checked-in bindings from {}", path.display()))?;
    if !binding_contents_equal(&checked_in, generated) {
        anyhow::bail!(
            "{} differs from the canonical BindingSpec output; run `xtask verify-bindings --update`",
            path.display()
        );
    }
    Ok(())
}

fn require_byte_identical(label: &str, first: &str, second: &str) -> Result<()> {
    if first.as_bytes() != second.as_bytes() {
        anyhow::bail!("{label} is not deterministic across two independent canonical generations");
    }
    Ok(())
}

fn binding_contents_equal(checked_in: &str, generated: &str) -> bool {
    normalize_line_endings(checked_in) == normalize_line_endings(generated)
}

fn normalize_line_endings(contents: &str) -> Cow<'_, str> {
    if contents.contains('\r') {
        Cow::Owned(contents.replace("\r\n", "\n").replace('\r', "\n"))
    } else {
        Cow::Borrowed(contents)
    }
}

fn extension_bindgen_builder(root: &Path, spec: &CrateBindingSpec) -> Result<bindgen::Builder> {
    let crate_root = root.join(spec.crate_root());
    let cimgui_root = maintained_source_root(root, "dear-imgui-sys")?;
    let imgui_src = cimgui_root.join("imgui");
    let shim_root = root
        .join("target/binding-spec-headers/crates")
        .join(spec.deterministic_hash().replace(':', "-"));
    fs::create_dir_all(&shim_root)
        .with_context(|| format!("create binding header shim dir {}", shim_root.display()))?;
    for shim in spec.header_shims {
        fs::write(shim_root.join(shim.name), shim.contents)
            .with_context(|| format!("write binding header shim {}", shim.name))?;
    }
    let profile = spec.profile;
    let mut builder = bindgen::Builder::default();
    builder = match profile.formatter {
        BindingFormatter::Rustfmt => builder.formatter(bindgen::Formatter::Rustfmt),
    };
    builder = match profile.rust_edition {
        BindingRustEdition::Rust2021 => builder.rust_edition(bindgen::RustEdition::Edition2021),
    };
    builder = builder
        .derive_default(profile.derives.default)
        .derive_debug(profile.derives.debug)
        .derive_copy(profile.derives.copy)
        .derive_eq(profile.derives.eq)
        .derive_partialeq(profile.derives.partial_eq)
        .derive_hash(profile.derives.hash)
        .prepend_enum_name(profile.prepend_enum_name)
        .layout_tests(profile.layout_tests)
        .allowlist_recursively(profile.allowlist_recursively);

    builder = builder.clang_arg(format!("-I{}", shim_root.display()));
    for arg in spec.clang_args {
        builder = builder.clang_arg(*arg);
    }

    for header in spec.input_paths {
        builder = builder.header(crate_root.join(header).to_string_lossy());
    }

    let source_root = crate_root.join(spec.source_root());
    for include in profile.include_paths {
        let root = match include.root {
            CrateBindingIncludeRoot::CoreCimgui => &cimgui_root,
            CrateBindingIncludeRoot::CoreImgui => &imgui_src,
            CrateBindingIncludeRoot::Source => &source_root,
        };
        builder = builder.clang_arg(format!("-I{}", root.join(include.relative_path).display()));
    }
    for define in spec.binding_defines() {
        builder = builder.clang_arg(define.clang_arg());
    }
    for pattern in profile.allowlisted_functions {
        builder = builder.allowlist_function(pattern);
    }
    for pattern in profile.allowlisted_types {
        builder = builder.allowlist_type(pattern);
    }
    for pattern in profile.allowlisted_vars {
        builder = builder.allowlist_var(pattern);
    }
    for pattern in profile.blocklisted_types {
        builder = builder.blocklist_type(pattern);
    }
    if profile.language == CrateBindingLanguage::Cxx17 {
        builder = builder
            .clang_arg("-x")
            .clang_arg("c++")
            .clang_arg("-std=c++17");
    }
    if let CrateBindingTarget::WasmImport { module_name } = spec.target {
        builder = builder.wasm_import_module_name(module_name);
    }
    Ok(builder)
}

fn generate_extension_bindings(
    root: &Path,
    spec: &CrateBindingSpec,
    output: &Path,
) -> Result<String> {
    let environment_names = std::env::vars_os()
        .map(|(name, _)| name.to_string_lossy().into_owned())
        .collect::<Vec<_>>();
    validate_bindgen_environment(&environment_names).map_err(anyhow::Error::msg)?;
    let bindings = extension_bindgen_builder(root, spec)?
        .generate()
        .with_context(|| {
            format!(
                "bindgen generate() failed for {} {}",
                spec.crate_name,
                spec.target.id()
            )
        })?;
    bindings
        .write_to_file(output)
        .with_context(|| format!("write bindings to {}", output.display()))?;
    let generated = fs::read_to_string(output)
        .with_context(|| format!("read generated bindings from {}", output.display()))?;
    let sanitized = sanitize_extension_bindings(&generated);
    let crate_root = root.join(spec.crate_root());
    let stamped = spec
        .stamp(&crate_root, &sanitized)
        .map_err(anyhow::Error::msg)?;
    fs::write(output, &stamped)
        .with_context(|| format!("write stamped bindings to {}", output.display()))?;
    Ok(stamped)
}

fn sanitize_extension_bindings(content: &str) -> String {
    let mut output = String::with_capacity(content.len());
    let mut skip_next_blank = false;
    for line in content.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("#![") {
            skip_next_blank = true;
            continue;
        }
        if skip_next_blank && trimmed.is_empty() {
            continue;
        }
        skip_next_blank = false;
        output.push_str(line);
        output.push('\n');
    }
    output
}

fn gen_implot_wasm_bindings() -> Result<()> {
    generate_maintained_wasm_binding(BindingOwner::Extension(ExtensionBinding::ImPlot))
}

fn gen_implot3d_wasm_bindings() -> Result<()> {
    generate_maintained_wasm_binding(BindingOwner::Extension(ExtensionBinding::ImPlot3d))
}

fn gen_imnodes_wasm_bindings() -> Result<()> {
    generate_maintained_wasm_binding(BindingOwner::Extension(ExtensionBinding::ImNodes))
}

fn gen_imguizmo_wasm_bindings() -> Result<()> {
    generate_maintained_wasm_binding(BindingOwner::Extension(ExtensionBinding::ImGuizmo))
}

fn gen_imguizmo_quat_wasm_bindings() -> Result<()> {
    generate_maintained_wasm_binding(BindingOwner::Extension(ExtensionBinding::ImGuizmoQuat))
}

fn generate_maintained_wasm_binding(owner: BindingOwner) -> Result<()> {
    let root = project_root();
    let spec = CrateBindingSpec::for_owner(owner)
        .find(|spec| spec.target.id() == "wasm")
        .ok_or_else(|| anyhow::anyhow!("no maintained WASM binding profile for {owner:?}"))?;
    let output = root.join(spec.crate_root()).join(spec.checked_in_path);
    eprintln!(
        "Generating {} WASM bindings to {} (import module: {})",
        spec.crate_name,
        output.display(),
        spec.target.import_module().unwrap_or_default()
    );
    generate_extension_bindings(&root, spec, &output)?;
    eprintln!("Done.");
    Ok(())
}

fn build_web_demo(features: Option<&str>) -> Result<()> {
    use std::fs;
    use std::process::Command;

    let root = project_root();
    let profile = std::env::var("PROFILE").unwrap_or_else(|_| "debug".into());

    // Ensure pregenerated wasm bindings exist for import-style linking (imgui-sys-v0)
    // If missing, generate them now so dear-imgui-sys does not attempt to bindgen for wasm.
    {
        let preg = maintained_crate_root(&root, "dear-imgui-sys")?
            .join("src")
            .join("wasm_bindings_pregenerated.rs");
        if !preg.exists() {
            eprintln!("Generating pregenerated wasm bindings (import module: imgui-sys-v0)...");
            gen_wasm_bindings()?;
        }
    }

    // 1) Build the web demo crate for wasm32-unknown-unknown
    eprintln!("Building dear-imgui-web-demo ({profile})...");
    // Determine which features to enable on the web demo crate.
    // Always enable the web-backends, and allow callers to opt into
    // additional extensions (e.g. implot) via a simple comma-separated list.
    let mut feature_list: Vec<String> = vec!["web-backends".to_string()];
    if let Some(extra) = features {
        for f in extra.split(',') {
            let f = f.trim();
            if !f.is_empty() && !feature_list.iter().any(|e| e == f) {
                feature_list.push(f.to_string());
            }
        }
    }
    let feature_str = feature_list.join(",");

    let mut build_cmd = Command::new("cargo");
    let status = build_cmd
        .args([
            "build",
            "-p",
            "dear-imgui-web-demo",
            "--target",
            "wasm32-unknown-unknown",
            "--no-default-features",
            "--features",
            &feature_str,
        ])
        .status()?;
    if !status.success() {
        anyhow::bail!("cargo build failed");
    }

    // 2) Run wasm-bindgen on the produced wasm
    // Package name as declared in examples-wasm/Cargo.toml
    let pkg_name = "dear-imgui-web-demo";
    // Rust artifact file stem uses underscores
    let wasm_name = pkg_name.replace('-', "_");
    let wasm_path = root
        .join("target")
        .join("wasm32-unknown-unknown")
        .join(&profile)
        .join(format!("{}.wasm", wasm_name));
    if !wasm_path.exists() {
        anyhow::bail!("wasm artifact not found: {}", wasm_path.display());
    }

    let dist = root.join("target").join("web-demo");
    // Clean old outputs to avoid stale/mismatched JS/WASM pairs
    if dist.exists() {
        eprintln!("Cleaning old web-demo dir: {}", dist.display());
        let _ = fs::remove_dir_all(&dist);
    }
    fs::create_dir_all(&dist)?;

    eprintln!("Running wasm-bindgen -> {}", dist.display());
    let status = Command::new("wasm-bindgen")
        .args([
            "--target",
            "web",
            "--no-typescript",
            "--out-name",
            pkg_name,
            "--out-dir",
            dist.to_str().unwrap(),
            wasm_path.to_str().unwrap(),
        ])
        .status()?;
    if !status.success() {
        anyhow::bail!("wasm-bindgen failed (install via `cargo install -f wasm-bindgen-cli`)");
    }

    // 2b) Rewrite the generated wasm to import memory from `env` so we can share memory
    // with the Emscripten-built provider (imgui-sys-v0). wasm-bindgen 0.2.104 no longer
    // exposes `--import-memory`, so we do a small WAT roundtrip:
    //   - Insert `(import "env" "memory" (memory ...))` right after `(module` (imports must be first)
    //   - Insert `(export "memory" (memory 0))`
    //   - Remove the original `(memory ...)` and its existing export if present
    // wasm-bindgen may emit either hyphen or underscore versioned filenames in JS.
    // Patch both variants if present, prioritizing the one referenced by the JS (hyphenated).
    let main_bg_wasm_hyphen = dist.join(format!("{}{}_bg.wasm", pkg_name, ""));
    let main_bg_wasm_underscore = dist.join(format!("{}_bg.wasm", pkg_name.replace('-', "_")));

    let mut candidates = vec![];
    if main_bg_wasm_hyphen.exists() {
        candidates.push(main_bg_wasm_hyphen.clone());
    }
    if main_bg_wasm_underscore.exists() {
        candidates.push(main_bg_wasm_underscore.clone());
    }

    if candidates.is_empty() {
        anyhow::bail!("wasm-bindgen bg.wasm not found (checked hyphen and underscore variants)");
    }

    for main_bg_wasm in candidates {
        let wat_path = dist.join("__wasm_tmp.wat");
        let patched_wat_path = dist.join("__wasm_tmp_patched.wat");
        // Print to WAT
        let ok = Command::new("wasm-tools")
            .args([
                "print",
                main_bg_wasm.to_str().unwrap(),
                "-o",
                wat_path.to_str().unwrap(),
            ])
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
        if ok {
            let mut wat = std::fs::read_to_string(&wat_path).unwrap_or_default();
            if !wat.contains("(import \"env\" \"memory\" (memory") {
                // Find original memory line to derive initial/max
                let mut original_mem_line_idx: Option<usize> = None;
                // Use safe defaults to avoid starving the provider (too-small max leads to OOM)
                let init_pages: String = "256".to_string();
                let max_pages: String = "4096".to_string();
                for (idx, line) in wat.lines().enumerate() {
                    let t = line.trim_start();
                    if t.starts_with("(memory") {
                        original_mem_line_idx = Some(idx);
                        break;
                    }
                }

                if let Some(mem_idx) = original_mem_line_idx {
                    let mut lines: Vec<String> = wat.lines().map(|s| s.to_string()).collect();
                    // Remove original memory line
                    lines.remove(mem_idx);
                    // Also remove any existing memory export to avoid duplicate
                    lines.retain(|l| l.trim() != "(export \"memory\" (memory 0))");
                    // Insert import + export right after the `(module` line (imports must come first)
                    if let Some(module_idx) = lines
                        .iter()
                        .position(|l| l.trim_start().starts_with("(module"))
                    {
                        let insert_at = module_idx + 1;
                        lines.insert(
                            insert_at,
                            format!(
                                "  (import \"env\" \"memory\" (memory (;0;) {} {}))",
                                init_pages, max_pages
                            ),
                        );
                        lines.insert(
                            insert_at + 1,
                            "  (export \"memory\" (memory 0))".to_string(),
                        );
                        wat = lines.join("\n");
                        std::fs::write(&patched_wat_path, &wat)?;
                        let ok2 = Command::new("wasm-tools")
                            .args([
                                "parse",
                                patched_wat_path.to_str().unwrap(),
                                "-o",
                                main_bg_wasm.to_str().unwrap(),
                            ])
                            .status()
                            .map(|s| s.success())
                            .unwrap_or(false);
                        if ok2 {
                            eprintln!(
                                "Patched {} to import memory from env",
                                main_bg_wasm.display()
                            );
                        } else {
                            eprintln!(
                                "Warning: failed to assemble patched WAT; leaving wasm unmodified"
                            );
                        }
                    } else {
                        eprintln!(
                            "Warning: failed to locate (module ...) header; skipping memory import patch"
                        );
                    }
                } else {
                    eprintln!("Warning: failed to find a (memory ...) declaration to patch");
                }
            }
            let _ = std::fs::remove_file(&wat_path);
            let _ = std::fs::remove_file(&patched_wat_path);
        } else {
            anyhow::bail!(
                "wasm-tools not found or failed to print WAT; cannot patch memory import.\nInstall with: cargo install wasm-tools"
            );
        }
    }

    // 3) Copy demo index.html
    let index_src = root.join("examples-wasm/web/index.html");
    let index_dst = dist.join("index.html");
    fs::copy(&index_src, &index_dst)?;

    // 3b) Patch generated JS to wire shared memory into wasm-bindgen init
    let js_main = dist.join(format!("{}.js", pkg_name));
    if js_main.exists() {
        let mut code = fs::read_to_string(&js_main)?;
        // Ensure we hand a shared memory to the module as `env.memory` so the provider (emscripten)
        // and main module use the same memory.
        if !code.contains("__imgui_shared_memory") {
            // Try to find the wasm-bindgen imports function header across versions
            let header_pos = code
                .find("function __wbg_get_imports()")
                .or_else(|| code.find("function getImports()"));

            // Choose insertion point: right after "const imports = {};" inside the function body
            let mut insert_at: Option<usize> = None;
            if let Some(h) = header_pos {
                // Search for the first occurrence of the marker after the header
                if let Some(rel) = code[h..].find("const imports = {};") {
                    insert_at = Some(h + rel + "const imports = {};".len());
                } else if let Some(open_idx) = code[h..].find("{\n") {
                    // Fallback: insert right after opening brace
                    insert_at = Some(h + open_idx + 2);
                }
            }
            // Last resort: search globally for the marker
            if insert_at.is_none()
                && let Some(global_rel) = code.find("const imports = {};")
            {
                insert_at = Some(global_rel + "const imports = {};".len());
            }

            if let Some(pos) = insert_at {
                let inject = r#"
        // Inject shared memory for import-style provider (imgui-sys-v0)
        const __shared_mem = globalThis.__imgui_shared_memory || new WebAssembly.Memory({ initial: 256, maximum: 4096 });
        if (!imports.env) imports.env = {};
        if (!imports.env.memory) imports.env.memory = __shared_mem;
"#;
                code.insert_str(pos, inject);
                eprintln!(
                    "Patched wasm-bindgen imports in {} to provide env.memory",
                    js_main.display()
                );
            } else {
                anyhow::bail!(
                    "Failed to locate insertion point in {} for memory injection (searched for __wbg_get_imports/getImports and 'const imports = {{}};')",
                    js_main.display()
                );
            }
        }
        fs::write(&js_main, &code)?;
    }

    eprintln!("Web demo built at: {}", dist.display());
    eprintln!(
        "Serve this dir via any static server, e.g.\n  python -m http.server -d {} 8080",
        dist.display()
    );
    // Import-style build: remember to run `xtask build-cimgui-provider` to generate the provider.
    Ok(())
}

fn find_emsdk_tools() -> Result<(std::path::PathBuf, std::path::PathBuf, std::path::PathBuf)> {
    // 1) Prefer PATH discovery (works if user ran emsdk_env or added to PATH)
    let which = |name: &str| which::which(name).ok();
    if let (Some(empp), Some(emcc)) = (which("em++"), which("emcc")) {
        let emscripten_dir = emcc.parent().unwrap().to_path_buf();
        let em_config = emscripten_dir.join(".emscripten");
        return Ok((empp, emcc, em_config));
    }

    // 2) Fallback to EMSDK env var if provided
    if let Ok(root) = std::env::var("EMSDK") {
        let root = std::path::PathBuf::from(root);
        let emscripten = root.join("upstream").join("emscripten");
        let empp = if cfg!(windows) {
            emscripten.join("em++.bat")
        } else {
            emscripten.join("em++")
        };
        let emcc = if cfg!(windows) {
            emscripten.join("emcc.bat")
        } else {
            emscripten.join("emcc")
        };
        let em_config = emscripten.join(".emscripten");
        if empp.exists() && emcc.exists() {
            return Ok((empp, emcc, em_config));
        }
    }

    anyhow::bail!(
        "Failed to locate emsdk tools (em++/emcc). On Windows, run emsdk_env.bat (or emsdk_env.ps1) to add them to PATH, or set EMSDK env var to your emsdk root."
    )
}

#[derive(Debug)]
struct WasmProviderInputs {
    module_name: String,
    exports: BTreeSet<String>,
    compile_defines: Vec<String>,
    include_dirs: Vec<PathBuf>,
    source_files: Vec<PathBuf>,
}

fn insert_provider_compile_define(
    defines: &mut BTreeMap<String, Option<String>>,
    define: CrateBindingDefine<'_>,
    source: &str,
) -> Result<()> {
    let value = define.value.map(str::to_owned);
    if let Some(existing) = defines.get(define.name) {
        if existing != &value {
            anyhow::bail!(
                "WebAssembly provider define {} conflicts between maintained profiles: {:?} vs {:?} from {source}",
                define.name,
                existing,
                value
            );
        }
        return Ok(());
    }
    defines.insert(define.name.to_owned(), value);
    Ok(())
}

#[derive(Debug, PartialEq, Eq)]
struct BuildProviderOptions {
    source_root: PathBuf,
    inventory_path: Option<PathBuf>,
    out_dir: PathBuf,
}

impl BuildProviderOptions {
    fn parse(project_root: &Path, arguments: &[String]) -> Result<Self> {
        let mut source_root = None;
        let mut inventory_path = None;
        let mut out_dir = None;
        let mut index = 0;
        while index < arguments.len() {
            let option = arguments[index].as_str();
            let destination = match option {
                "--source-root" => &mut source_root,
                "--inventory" => &mut inventory_path,
                "--out-dir" => &mut out_dir,
                _ => anyhow::bail!("build-cimgui-provider does not accept option {option:?}"),
            };
            if destination.is_some() {
                anyhow::bail!("build-cimgui-provider option {option:?} was provided twice");
            }
            index += 1;
            let Some(value) = arguments.get(index) else {
                anyhow::bail!("build-cimgui-provider option {option:?} requires a path");
            };
            *destination = Some(PathBuf::from(value));
            index += 1;
        }

        Ok(Self {
            source_root: source_root.unwrap_or_else(|| project_root.to_path_buf()),
            inventory_path,
            out_dir: out_dir.unwrap_or_else(|| project_root.join("target").join("web-demo")),
        })
    }
}

fn prepare_wasm_provider_inputs(
    inventory: &build_support::source_inventory::SourceInventory,
    root: &Path,
    out_dir: &Path,
) -> Result<WasmProviderInputs> {
    use build_support::source_inventory::{ProviderTransform, parse_wasm_imports};

    let mut exports = BTreeSet::new();
    let mut compile_defines = BTreeMap::new();
    let mut include_dirs = Vec::new();
    let mut source_files = Vec::new();

    let core_spec = BindingSpec::core_wasm(inventory.wasm_import_module.clone());
    for define in core_spec
        .clang_defines
        .iter()
        .filter_map(|definition| CrateBindingDefine::from_definition(definition))
        .filter(|define| define.applies_to_native_compilation())
    {
        insert_provider_compile_define(&mut compile_defines, define, "dear-imgui-sys")?;
    }
    for define in [
        CrateBindingDefine {
            name: "IMGUI_DEFINE_MATH_OPERATORS",
            value: Some("1"),
        },
        CrateBindingDefine {
            name: "IMNODES_NAMESPACE",
            value: Some("imnodes"),
        },
    ] {
        insert_provider_compile_define(&mut compile_defines, define, "provider runtime")?;
    }

    for source in inventory
        .sources
        .iter()
        .filter(|source| source.provider.is_some())
    {
        let provider = source.provider.as_ref().expect("filtered provider source");
        let crate_root = root.join(&source.crate_root);
        source.resolve_source_root(&crate_root)?;

        if source.crate_name != "dear-imgui-sys" {
            let spec = CrateBindingSpec::for_crate_and_target(&source.crate_name, "wasm")
                .ok_or_else(|| {
                    anyhow::anyhow!(
                        "{} declares a WebAssembly provider without a canonical wasm binding spec",
                        source.crate_name
                    )
                })?;
            for define in spec.native_binding_defines() {
                insert_provider_compile_define(&mut compile_defines, define, &source.crate_name)?;
            }
        }

        let bindings_path = crate_root.join(&provider.wasm_bindings);
        let bindings = fs::read_to_string(&bindings_path)
            .with_context(|| format!("read provider bindings {}", bindings_path.display()))?;
        let imports = parse_wasm_imports(&bindings, &inventory.wasm_import_module)
            .with_context(|| format!("validate provider imports for {}", source.crate_name))?;
        let unexpected = imports
            .symbols
            .iter()
            .filter(|symbol| {
                !provider
                    .symbol_prefixes
                    .iter()
                    .any(|prefix| symbol.starts_with(prefix))
            })
            .cloned()
            .collect::<Vec<_>>();
        if !unexpected.is_empty() {
            anyhow::bail!(
                "{} WebAssembly bindings contain imports outside the maintained symbol prefixes: {}",
                source.crate_name,
                unexpected.join(", ")
            );
        }
        exports.extend(imports.symbols);
        exports.extend(provider.required_exports.iter().cloned());

        for relative in &provider.include_dirs {
            let include_dir = crate_root.join(relative);
            if !include_dir.is_dir() {
                anyhow::bail!(
                    "{} provider include directory is missing: {}",
                    source.crate_name,
                    include_dir.display()
                );
            }
            if !include_dirs.contains(&include_dir) {
                include_dirs.push(include_dir);
            }
        }

        for provider_source in source.provider_sources(&crate_root)? {
            match provider_source.transform {
                ProviderTransform::Direct => source_files.push(provider_source.path),
                ProviderTransform::PatchImguiCore | ProviderTransform::PatchImguiDemo => {
                    let contents =
                        fs::read_to_string(&provider_source.path).with_context(|| {
                            format!("read provider source {}", provider_source.path.display())
                        })?;
                    let patched = match provider_source.transform {
                        ProviderTransform::PatchImguiCore => {
                            build_support::patch_imgui_cpp_for_safe_demo(&contents)
                        }
                        ProviderTransform::PatchImguiDemo => {
                            build_support::patch_imgui_demo_cpp_for_safe_demo(&contents)
                        }
                        ProviderTransform::Direct => unreachable!(),
                    }
                    .map_err(anyhow::Error::msg)?;
                    let patched_path = out_dir.join(format!(
                        "provider-{}-{}-patched.cpp",
                        source.id, provider_source.id
                    ));
                    fs::write(&patched_path, patched).with_context(|| {
                        format!("write patched provider source {}", patched_path.display())
                    })?;
                    source_files.push(patched_path);
                }
            }
        }
    }

    if exports.is_empty() || source_files.is_empty() {
        anyhow::bail!("maintained-source inventory produced an empty WebAssembly provider");
    }
    Ok(WasmProviderInputs {
        module_name: inventory.wasm_import_module.clone(),
        exports,
        compile_defines: compile_defines
            .into_iter()
            .map(|(name, value)| match value {
                Some(value) => format!("-D{name}={value}"),
                None => format!("-D{name}"),
            })
            .collect(),
        include_dirs,
        source_files,
    })
}

fn build_cimgui_provider(options: BuildProviderOptions) -> Result<()> {
    use std::fs;
    use std::process::Command;

    use build_support::source_inventory::SourceInventory;

    let BuildProviderOptions {
        source_root,
        inventory_path,
        out_dir,
    } = options;
    fs::create_dir_all(&out_dir)?;
    let loaded_inventory = inventory_path
        .as_ref()
        .map(|path| {
            let contents = fs::read_to_string(path)
                .with_context(|| format!("read provider inventory {}", path.display()))?;
            SourceInventory::parse(&contents)
                .with_context(|| format!("parse provider inventory {}", path.display()))
        })
        .transpose()?;
    let inventory = loaded_inventory
        .as_ref()
        .unwrap_or_else(|| SourceInventory::embedded());

    // 1) Locate emsdk tools and ensure emscripten config exists
    let (empp, emcc, em_config) = find_emsdk_tools()?;
    // Newer emsdk setups may already have a global .emscripten config in the
    // root EMSDK dir. In that case `emcc --generate-config` will fail with
    // "config file already exists". Treat that as a non-fatal condition and
    // rely on the existing config instead of bailing.
    let mut use_custom_em_config = false;
    if em_config.exists() {
        use_custom_em_config = true;
    } else {
        eprintln!("Generating Emscripten config at {}", em_config.display());
        let status = Command::new(&emcc)
            .arg("--generate-config")
            .arg(&em_config)
            .status()?;
        if status.success() {
            use_custom_em_config = true;
        } else {
            eprintln!(
                "Warning: emcc --generate-config failed; \
                 continuing with existing EMSDK configuration"
            );
        }
    }

    // 2) Resolve every provider source and Rust import from the checked-in inventory.
    let WasmProviderInputs {
        module_name,
        exports: names,
        compile_defines,
        include_dirs,
        source_files,
    } = prepare_wasm_provider_inputs(inventory, &source_root, &out_dir)?;
    let out_js = out_dir.join(format!("{module_name}.js"));

    // Emscripten expects C exports with the JavaScript ABI underscore prefix.
    let exported = names
        .iter()
        .map(|name| format!("_{name}"))
        .collect::<Vec<_>>();
    let exports_json = format!(
        "[{}]",
        exported
            .iter()
            .map(|symbol| format!("\"{symbol}\""))
            .collect::<Vec<_>>()
            .join(",")
    );
    let exports_path = out_dir.join("imgui_exports.json");
    fs::write(&exports_path, &exports_json)?;

    // 2b) Compose em++ command to build imgui-sys-v0.wasm (shared imported memory) with explicit exports

    let mut cmd = Command::new(&empp);
    cmd.arg("-std=c++17")
        .arg("-O2")
        .arg("-s")
        .arg("MODULARIZE=1")  // Generate a module function
        .arg("-s")
        .arg("EXPORT_ES6=1")  // Export as ES6 module
        .arg("-s")
        .arg("ENVIRONMENT=web")
        .arg("-s")
        .arg("GLOBAL_BASE=67108864") // Place provider static data high to avoid overlap with main module
        .arg("-s")
        .arg("IMPORTED_MEMORY=1")
        .arg("-s")
        .arg("ALLOW_MEMORY_GROWTH=1")
        .arg("-s")
        .arg("INITIAL_MEMORY=134217728")
        .arg("-s")
        .arg("FILESYSTEM=0")
        .arg("-s")
        .arg("NO_EXIT_RUNTIME=1")
        .arg("-s")
        .arg("MALLOC=emmalloc")
        .arg("-s")
        .arg("ASSERTIONS=1")
        .arg("-s")
        .arg("STACK_SIZE=1048576")
        .arg("-s")
        .arg("EXPORTED_RUNTIME_METHODS=[\"ccall\",\"cwrap\",\"allocate\",\"stackSave\",\"stackRestore\",\"stackAlloc\",\"UTF8ToString\",\"stringToUTF8\",\"lengthBytesUTF8\"]")
        .arg("-s")
        .arg(format!(
            "EXPORTED_FUNCTIONS=@{}",
            exports_path
                .to_string_lossy()
                .replace('\\', "/") // emscripten on Windows accepts fwd slashes
        ))
        .arg("-fno-exceptions")
        .arg("-fno-rtti");
    for define in &compile_defines {
        cmd.arg(define);
    }
    for include_dir in &include_dirs {
        cmd.arg("-I").arg(include_dir);
    }
    for source_file in &source_files {
        cmd.arg(source_file);
    }
    cmd.arg("-o").arg(&out_js);

    // Ensure tools can find config and binaries
    let emscripten_dir = emcc.parent().unwrap();
    let tool_bin = emscripten_dir.parent().unwrap().join("bin");
    let path = std::env::var_os("PATH").unwrap_or_default();
    let new_path = {
        let mut p = std::env::split_paths(&path).collect::<Vec<_>>();
        p.insert(0, emscripten_dir.to_path_buf());
        p.insert(0, tool_bin);
        std::env::join_paths(p).unwrap()
    };
    cmd.env("PATH", new_path);
    if use_custom_em_config {
        cmd.env("EM_CONFIG", &em_config);
    }

    eprintln!("Building cimgui provider -> {}", out_js.display());
    let status = cmd.status()?;
    if !status.success() {
        anyhow::bail!("em++ failed; see output for details");
    }

    // 3) Verify the actual provider binary before generating its JavaScript wrapper.
    let emscripten_js = out_dir.join(format!("{module_name}.js"));
    if !emscripten_js.exists() {
        anyhow::bail!("Emscripten output not found: {}", emscripten_js.display());
    }
    let emscripten_wasm = out_dir.join(format!("{module_name}.wasm"));
    let provider_bytes = fs::read(&emscripten_wasm)
        .with_context(|| format!("read Emscripten output {}", emscripten_wasm.display()))?;
    let actual_exports = build_support::source_inventory::parse_wasm_exports(&provider_bytes)
        .with_context(|| format!("parse provider exports from {}", emscripten_wasm.display()))?;
    build_support::source_inventory::verify_emscripten_wasm_exports(
        &actual_exports,
        names.iter().map(String::as_str),
    )
    .with_context(|| {
        format!(
            "verify {} Rust imports against the built provider",
            names.len()
        )
    })?;

    // Create wrapper module
    let wrapper_name = format!("{module_name}-wrapper.js");
    let js_path = out_dir.join(&wrapper_name);
    let mut js = String::new();
    js.push_str(&format!(
        "// Auto-generated wrapper for {module_name} provider\n"
    ));
    js.push_str(&format!("import createModule from './{module_name}.js';\n"));
    js.push('\n');
    js.push_str("// Use shared memory if available\n");
    js.push_str("const memory = globalThis.__imgui_shared_memory || new WebAssembly.Memory({initial:256, maximum:4096});\n");
    js.push('\n');
    js.push_str("// Initialize the module with shared memory\n");
    js.push_str("const Module = await createModule({\n");
    js.push_str("  wasmMemory: memory,\n");
    js.push_str(&format!(
        "  printErr: (text) => console.warn('[{module_name}]', text),\n"
    ));
    js.push_str(&format!(
        "  print: (text) => console.log('[{module_name}]', text),\n"
    ));
    js.push_str("});\n");
    js.push_str(&format!(
        "console.log('[{module_name}] Shared memory pages=', (memory.buffer.byteLength>>>16));\n"
    ));
    js.push_str(&format!(
        "console.log('[{module_name}] Module.wasmMemory===memory', Module.wasmMemory===memory);\n"
    ));
    js.push('\n');
    js.push_str("// Export all the functions\n");
    for n in &names {
        js.push_str(&format!(
            "export const {} = Module._{} || Module.{};\n",
            n, n, n
        ));
    }
    fs::write(&js_path, js)?;
    eprintln!(
        "Wrote provider module: {} ({} exports)",
        js_path.display(),
        names.len()
    );

    // 4) Ensure the generated web demo imports the maintained provider module.
    let index = out_dir.join("index.html");
    if index.exists() {
        let mut html = fs::read_to_string(&index)?;
        // Desired importmap snippet (no escaping in HTML) pointing to .js for better MIME defaults
        let importmap = format!(
            r#"<script type="importmap">{{
  "imports": {{
    "{module_name}": "./{wrapper_name}"
  }}
}}</script>"#
        );

        // If an older, incorrectly-escaped importmap exists, normalize it by
        // replacing the escaped variant with the correct snippet.
        let escaped_marker = "type=\\\"importmap\\\"";
        // Best-effort fix: drop any lingering escaped sequences from a prior bad patch
        if html.contains(escaped_marker) || html.contains("\\\"") || html.contains("\\n") {
            if html.contains(escaped_marker) {
                html = html.replace(escaped_marker, "type=\"importmap\"");
            }
            html = html.replace("\\\"", "\"");
            html = html.replace("\\n", "\n");
            fs::write(&index, &html)?;
            eprintln!("Normalized previously escaped importmap in index.html");
        }

        // Replace legacy .mjs or .js mapping to wrapper if present
        let legacy_mjs = format!("{module_name}.mjs");
        let provider_js = format!("{module_name}.js");
        if html.contains(&legacy_mjs) || html.contains(&provider_js) {
            html = html.replace(&legacy_mjs, &wrapper_name);
            html = html.replace(&provider_js, &wrapper_name);
            fs::write(&index, &html)?;
            eprintln!("Updated importmap to use wrapper for {module_name}");
        }

        // Inject importmap if it's still missing
        // Import map must be placed BEFORE any module scripts
        if !html.contains(&wrapper_name) && !html.contains("type=\"importmap\"") {
            // Insert import map right after the closing </style> tag, before the body
            html = html.replace(
                "</style>\n  </head>",
                &format!("</style>\n{importmap}\n  </head>"),
            );
            fs::write(&index, html)?;
            eprintln!("Patched index.html with importmap for {module_name}");
        }
    } else {
        eprintln!(
            "Warning: {} not found; provider module generated, but importmap not injected.",
            index.display()
        );
    }

    eprintln!("cimgui provider ready -> open target/web-demo/index.html");
    Ok(())
}

fn main() {
    if let Err(e) = run() {
        eprintln!("xtask error: {e:?}");
        std::process::exit(1);
    }
}

#[cfg(test)]
mod tests {
    use super::{
        BuildProviderOptions, VerifyBindingOptions, binding_contents_equal,
        prepare_wasm_provider_inputs, project_root, require_byte_identical,
    };
    use build_support::source_inventory::SourceInventory;
    use std::path::PathBuf;

    fn args(values: &[&str]) -> Vec<String> {
        values.iter().map(|value| (*value).to_owned()).collect()
    }

    #[test]
    fn provider_inputs_cover_all_checked_in_imports_and_canonical_sources() {
        let output = tempfile::tempdir().unwrap();
        let inputs = prepare_wasm_provider_inputs(
            SourceInventory::embedded(),
            &project_root(),
            output.path(),
        )
        .unwrap();
        assert_eq!(inputs.module_name, "imgui-sys-v0");
        assert!(inputs.exports.contains("ImGuizmo_ComputeMouseRay"));
        assert!(
            inputs
                .exports
                .contains("EmulateThreeButtonMouse_EmulateThreeButtonMouse")
        );
        assert!(inputs.exports.contains("Style_Style"));
        for symbol in [
            "ImPlot_Annotation_Str0",
            "ImPlot_TagX_Str0",
            "ImPlot_TagY_Str0",
        ] {
            assert!(inputs.exports.contains(symbol), "missing export {symbol}");
        }
        assert!(
            inputs
                .compile_defines
                .iter()
                .any(|define| define == "-DCIMGUI_VARGS0")
        );
        assert!(
            inputs
                .compile_defines
                .iter()
                .any(|define| define == "-DIMGUI_DISABLE_FILE_FUNCTIONS")
        );
        assert!(
            !inputs
                .compile_defines
                .iter()
                .any(|define| define == "-DCIMGUI_DEFINE_ENUMS_AND_STRUCTS")
        );
        assert!(
            inputs
                .source_files
                .iter()
                .any(|path| { path.ends_with("third-party/cimguizmo/ImGuizmo/src/ImGuizmo.cpp") })
        );
        assert!(
            inputs
                .source_files
                .iter()
                .any(|path| path.ends_with("imguizmo_quat.cpp"))
        );
        assert!(
            inputs
                .source_files
                .iter()
                .all(|path| !path.ends_with("imGuIZMOquat.cpp"))
        );
    }

    #[test]
    fn provider_options_support_packaged_source_inputs() {
        let root = project_root();
        assert_eq!(
            BuildProviderOptions::parse(&root, &[]).unwrap(),
            BuildProviderOptions {
                source_root: root.clone(),
                inventory_path: None,
                out_dir: root.join("target").join("web-demo"),
            }
        );
        assert_eq!(
            BuildProviderOptions::parse(
                &root,
                &args(&[
                    "--source-root",
                    "package-root",
                    "--inventory",
                    "package-inventory.json",
                    "--out-dir",
                    "provider-output",
                ]),
            )
            .unwrap(),
            BuildProviderOptions {
                source_root: PathBuf::from("package-root"),
                inventory_path: Some(PathBuf::from("package-inventory.json")),
                out_dir: PathBuf::from("provider-output"),
            }
        );
        assert!(BuildProviderOptions::parse(&root, &args(&["--source-root"])).is_err());
        assert!(
            BuildProviderOptions::parse(
                &root,
                &args(&["--source-root", "one", "--source-root", "two"]),
            )
            .is_err()
        );
    }

    #[test]
    fn verify_binding_options_parse_supported_modes() {
        assert_eq!(
            VerifyBindingOptions::parse(&args(&["--check-only", "--allow-dirty"])).unwrap(),
            VerifyBindingOptions {
                check_only: true,
                allow_dirty: true,
                update: false,
            }
        );
        assert_eq!(
            VerifyBindingOptions::parse(&args(&["--update", "--allow-dirty"])).unwrap(),
            VerifyBindingOptions {
                check_only: false,
                allow_dirty: true,
                update: true,
            }
        );
        assert!(VerifyBindingOptions::parse(&args(&["--update", "--check-only"])).is_err());
        assert!(VerifyBindingOptions::parse(&args(&["--unknown"])).is_err());
    }

    #[test]
    fn binding_comparison_ignores_only_line_ending_style() {
        assert!(binding_contents_equal(
            "first\r\nsecond\r\n",
            "first\nsecond\n"
        ));
        assert!(binding_contents_equal("first\rsecond\r", "first\nsecond\n"));
        assert!(!binding_contents_equal(
            "first\r\nsecond\r\n",
            "first\nchanged\n"
        ));
    }

    #[test]
    fn independent_generation_requires_exact_bytes() {
        require_byte_identical("fixture", "first\nsecond\n", "first\nsecond\n").unwrap();
        assert!(require_byte_identical("fixture", "first\n", "changed\n").is_err());
        assert!(require_byte_identical("fixture", "first\r\n", "first\n").is_err());
    }
}
