[package]
name = "dear-imgui-glow"
version.workspace = true
edition.workspace = true
description = "Glow (OpenGL) renderer backend for dear-imgui-rs"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
documentation = "https://docs.rs/dear-imgui-glow"
categories.workspace = true
keywords.workspace = true

[dependencies]
dear-imgui-rs.workspace = true
glow.workspace = true
thiserror.workspace = true

[features]
default = []

# Select the explicit import-style Dear ImGui provider on WebAssembly targets.
wasm = ["dear-imgui-rs/wasm"]

# Owning multi-viewport renderer runtime (off by default)
multi-viewport = ["dear-imgui-rs/multi-viewport"]

[dev-dependencies]
dear-imgui-winit.workspace = true
env_logger.workspace = true
glutin.workspace = true
glutin-winit.workspace = true
pollster.workspace = true
raw-window-handle.workspace = true
static_assertions = "1.1"
winit.workspace = true
